#!/usr/bin/env python3
"""Generate daily AI news report from cached JSON and push to Feishu.

Hybrid architecture (local stage only):
- Read candidate news JSON generated by GitHub Actions.
- Call LiteLLM via company gateway to produce one compact JSON report.
- Send exactly one Feishu message (interactive card, fallback post, fallback text).
"""

from __future__ import annotations

import base64
import difflib
import hashlib
import hmac
import json
import logging
import os
import re
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse
from urllib.request import Request, urlopen
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


LOGGER = logging.getLogger("daily_ai_news")

DEFAULT_HTTP_TIMEOUT_SECONDS = 25
DEFAULT_LLM_PROVIDER = "litellm"
DEFAULT_LLM_TIMEOUT_SECONDS = 60
DEFAULT_LLM_MAX_RETRIES = 1
DEFAULT_ENABLE_RULE_BASED_FALLBACK = True
MAX_CANDIDATES_FOR_PROMPT = 24
MAX_LEARNING_CANDIDATES_FOR_PROMPT = 12
FALLBACK_SCAN_DAYS = 14

DEFAULT_TIMEZONE = "Asia/Shanghai"
DEFAULT_NEWS_MAX_CHARS = 3500
DEFAULT_NEWS_TOP_N = 5
DEFAULT_MAX_ITEMS_FOR_LLM = 5

DEFAULT_LEARNING_NOTE = "基于标题和摘要整理，建议打开原链接查看完整内容。"
DEFAULT_LEARNING_EMPTY_TEXT = "今日未发现高质量 Agent 概念学习资源。"

RELATION_DIRECT = "直接影响"
RELATION_INDIRECT = "间接影响"
RELATION_NONE = "暂无明显影响"
VALID_RELATIONS = {RELATION_DIRECT, RELATION_INDIRECT, RELATION_NONE}

LEARNING_TYPE_YOUTUBE = "YouTube 视频"
LEARNING_TYPE_OFFICIAL = "官方文档"
LEARNING_TYPE_OFFICIAL_VIDEO = "官方视频"
LEARNING_TYPE_BLOG = "博客"
LEARNING_TYPE_TECH_BLOG = "技术博客"
LEARNING_TYPE_TUTORIAL = "教程"
LEARNING_TYPE_NEWS = "新闻"
LEARNING_TYPE_NA = "N/A"

LEARNING_CORE_KEYWORDS = [
    "codex",
    "agent",
    "cli",
    "mcp",
    "agents.md",
    "workflow",
    "code review",
    "代码审查",
    "工作流",
]

CONCEPT_HINT_RULES: list[tuple[set[str], str]] = [
    ({"agents_sdk", "agent_workflow", "openai_agents"}, "Agent Workflow"),
    ({"tool_calling", "tools", "tool_integration"}, "Tool Calling"),
    ({"guardrails", "safety", "approvals"}, "Guardrails"),
    ({"human_in_the_loop", "approvals"}, "Human-in-the-loop"),
    ({"evals", "agent_evaluation", "graders", "datasets"}, "Agent Evaluation"),
    ({"observability", "tracing", "debugging"}, "Observability"),
    ({"mcp", "integrations", "external_tools"}, "MCP"),
    ({"agents_md", "agent_instructions", "project_context"}, "Agent Instructions"),
    ({"codex", "coding_agent", "cli", "local_agent"}, "Coding Agent"),
    ({"orchestration", "handoffs", "multi_agent", "agent_orchestration"}, "Orchestration"),
    ({"state", "context_management", "memory"}, "Agent State"),
    ({"agent_skills", "reusable_capabilities"}, "Agent Skills"),
]

CONCEPT_EXPLANATIONS: dict[str, dict[str, str]] = {
    "Agent Workflow": {
        "concept_explanation": "Agent Workflow 是把模型、工具、状态、决策和结果处理组织成连续任务流的方式。",
        "why_it_matters": "它让 AI 不只是回答问题，而是能围绕目标推进多步骤任务。",
        "auto_relevance": "可用于组织需求分析、测试执行、缺陷定位和工程数据处理等流程。",
        "example_scenario": "例如一个研发 Agent 先读取需求，再调用测试工具，最后汇总失败原因。",
    },
    "Tool Calling": {
        "concept_explanation": "Tool Calling 是让模型在需要时调用外部函数、API 或系统工具的机制。",
        "why_it_matters": "它让 Agent 能查询数据、执行动作并处理真实系统任务。",
        "auto_relevance": "可用于连接需求库、测试平台、缺陷系统、仿真工具和内部知识库。",
        "example_scenario": "例如 Agent 查询缺陷单后调用测试脚本，再整理定位结果。",
    },
    "Guardrails": {
        "concept_explanation": "Guardrails 是限制 Agent 行为边界的规则、检查或审批机制。",
        "why_it_matters": "它能降低错误操作、越权访问、不可靠输出和安全风险。",
        "auto_relevance": "适合用于安全关键软件、配置变更、测试发布和敏感数据访问场景。",
        "example_scenario": "例如 Agent 想修改配置文件前，需要通过规则检查或人工确认。",
    },
    "Human-in-the-loop": {
        "concept_explanation": "Human-in-the-loop 是在人类确认后再执行关键动作的机制。",
        "why_it_matters": "它在自动化效率和工程安全之间建立缓冲区。",
        "auto_relevance": "适合代码合入、测试发布、需求变更和安全相关决策。",
        "example_scenario": "例如 Agent 生成修复方案后，由工程师确认再执行修改。",
    },
    "Agent Evaluation": {
        "concept_explanation": "Agent Evaluation 是评估 Agent 在多步骤任务中的成功率、稳定性和安全性的过程。",
        "why_it_matters": "不能只看单次回答质量，还要看任务是否可靠完成。",
        "auto_relevance": "可用于评估研发 Agent 在日志分析、测试生成、缺陷定位中的效果。",
        "example_scenario": "例如用一组历史缺陷案例测试 Agent 是否能稳定定位问题。",
    },
    "Observability": {
        "concept_explanation": "Observability 是记录和观察 Agent 的决策、工具调用、失败点和中间状态。",
        "why_it_matters": "它让复杂 Agent 工作流可调试、可审计、可持续改进。",
        "auto_relevance": "适合用于追踪自动化测试、需求分析和故障诊断 Agent 的行为。",
        "example_scenario": "例如查看 Agent 哪一步调用了错误工具，导致测试结论不一致。",
    },
    "MCP": {
        "concept_explanation": "MCP 是一种让模型或 Agent 连接外部工具和上下文的协议思路。",
        "why_it_matters": "它统一工具接入方式，降低不同系统之间的集成复杂度。",
        "auto_relevance": "可用于连接代码仓库、测试系统、需求平台、仿真环境和文档库。",
        "example_scenario": "例如通过 MCP 让 Agent 同时访问代码、测试结果和缺陷系统。",
    },
    "Agent Instructions": {
        "concept_explanation": "Agent Instructions 是给 Agent 的项目级背景、约束和工作规则。",
        "why_it_matters": "它帮助 Agent 在具体项目中保持一致的工程上下文。",
        "auto_relevance": "适合表达代码规范、测试要求、安全边界和工具链限制。",
        "example_scenario": "例如在项目说明中定义哪些目录可改、哪些配置不能触碰。",
    },
    "Coding Agent": {
        "concept_explanation": "Coding Agent 是面向软件工程任务的 Agent，能理解代码仓库、修改文件、运行测试并反馈结果。",
        "why_it_matters": "它把 AI 从代码补全推进到任务级研发协作。",
        "auto_relevance": "可用于辅助脚本维护、测试补全、日志分析和工具链自动化。",
        "example_scenario": "例如 Agent 阅读测试失败日志，定位相关代码路径并提出修改建议。",
    },
    "Orchestration": {
        "concept_explanation": "Orchestration 是协调多个步骤、工具或 Agent 的机制。",
        "why_it_matters": "复杂任务需要拆解、路由、执行和结果合并，不能只靠单次模型回答。",
        "auto_relevance": "可用于把需求分析、代码检查、测试执行和报告生成串成工作流。",
        "example_scenario": "例如一个主 Agent 把任务分给测试 Agent、文档 Agent 和代码审查 Agent。",
    },
    "Agent State": {
        "concept_explanation": "Agent State 是 Agent 在任务过程中保留的上下文、进度和中间结果。",
        "why_it_matters": "它让多轮任务具备连续性，避免每一步都重新开始。",
        "auto_relevance": "适合长流程研发任务，例如跨多个模块的缺陷排查和测试跟踪。",
        "example_scenario": "例如 Agent 记住已检查过的日志、配置和测试结果，再继续下一步分析。",
    },
    "Agent Skills": {
        "concept_explanation": "Agent Skills 是可复用的能力单元，让 Agent 在类似任务中复用经验和流程。",
        "why_it_matters": "它能把常见任务沉淀成稳定能力，减少重复配置。",
        "auto_relevance": "可用于沉淀日志分析、测试生成、代码审查和发布检查等研发能力。",
        "example_scenario": "例如把分析失败测试并生成复现步骤沉淀成一个可复用技能。",
    },
    "AI Agent": {
        "concept_explanation": "AI Agent 是能围绕目标进行规划、调用工具、处理反馈并推进任务的 AI 系统。",
        "why_it_matters": "它把 AI 从单轮问答扩展到多步骤任务执行。",
        "auto_relevance": "可用于研发流程自动化、测试分析、文档处理和工程工具链协同。",
        "example_scenario": "例如 Agent 根据问题描述查找代码、读取日志并生成排查建议。",
    },
}

LEARNING_NEGATIVE_KEYWORDS = [
    "chatgpt",
    "game",
    "gaming",
    "movie",
    "trailer",
    "music",
    "娱乐",
    "游戏",
    "影视",
    "广告",
]


class LiteLLMReportParseError(RuntimeError):
    """Raised when LiteLLM content cannot be parsed into expected report JSON."""


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def load_dotenv_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if value.startswith(("'", '"')) and value.endswith(("'", '"')) and len(value) >= 2:
            value = value[1:-1]
        os.environ.setdefault(key, value)


def parse_int_env(name: str, default: int) -> int:
    raw = os.getenv(name, str(default)).strip()
    try:
        value = int(raw)
        if value <= 0:
            raise ValueError
        return value
    except ValueError:
        LOGGER.warning("%s invalid (%s), fallback to %s", name, raw, default)
        return default


def parse_nonnegative_int_env(name: str, default: int) -> int:
    raw = os.getenv(name, str(default)).strip()
    try:
        value = int(raw)
        if value < 0:
            raise ValueError
        return value
    except ValueError:
        LOGGER.warning("%s invalid (%s), fallback to %s", name, raw, default)
        return default


def parse_bool_env(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    text = raw.strip().lower()
    if text in {"1", "true", "yes", "y", "on"}:
        return True
    if text in {"0", "false", "no", "n", "off"}:
        return False
    LOGGER.warning("%s invalid (%s), fallback to %s", name, raw, default)
    return default


def get_timezone(tz_name: str) -> timezone:
    try:
        return ZoneInfo(tz_name)
    except ZoneInfoNotFoundError:
        if tz_name == DEFAULT_TIMEZONE:
            return timezone(timedelta(hours=8), name=tz_name)
        if tz_name.upper() == "UTC":
            return timezone.utc
        raise RuntimeError(f"Invalid TIMEZONE: {tz_name}")


def safe_endpoint_label(url: str) -> str:
    parsed = urlparse(url)
    return parsed.netloc or "unknown-host"


def normalize_url(url: str) -> str:
    value = (url or "").strip()
    if not value:
        return ""
    parsed = urlparse(value)
    tracking_keys = {
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_term",
        "utm_content",
        "fbclid",
        "gclid",
        "spm",
        "from",
        "source",
    }
    query = [
        (key, val)
        for key, val in parse_qsl(parsed.query, keep_blank_values=True)
        if key.lower() not in tracking_keys
    ]
    return urlunparse(
        (
            parsed.scheme.lower(),
            parsed.netloc.lower(),
            parsed.path.rstrip("/"),
            "",
            urlencode(query, doseq=True),
            "",
        )
    )


def clean_text(value: Any) -> str:
    text = str(value or "")
    text = text.replace("\r", "\n")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def truncate_text(text: str, max_len: int) -> str:
    text = clean_text(text)
    if max_len <= 0:
        return ""
    if len(text) <= max_len:
        return text
    if max_len == 1:
        return text[:1]
    return text[: max_len - 1].rstrip() + "…"


def http_post_json(
    url: str,
    payload: dict[str, Any],
    headers: dict[str, str] | None = None,
    timeout_seconds: int | None = None,
    retry_count: int = 0,
    retry_timeout_seconds: int | None = None,
) -> dict[str, Any]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req_headers = {"Content-Type": "application/json"}
    if headers:
        req_headers.update(headers)

    timeout_value = timeout_seconds or parse_int_env("HTTP_TIMEOUT_SECONDS", DEFAULT_HTTP_TIMEOUT_SECONDS)
    retry_timeout_value = retry_timeout_seconds or timeout_value
    attempts = max(retry_count, 0) + 1
    last_exc: Exception | None = None

    for attempt in range(1, attempts + 1):
        attempt_timeout = timeout_value if attempt == 1 else retry_timeout_value
        request = Request(url=url, data=data, headers=req_headers, method="POST")
        try:
            with urlopen(request, timeout=attempt_timeout) as response:
                body = response.read().decode("utf-8", errors="replace")
            break
        except HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
            raise RuntimeError(
                f"HTTP {exc.code} calling endpoint={safe_endpoint_label(url)}: {body[:200]}"
            ) from exc
        except TimeoutError as exc:
            last_exc = exc
            if attempt < attempts:
                LOGGER.warning(
                    "Request timed out calling endpoint=%s after %ss, retry %s/%s",
                    safe_endpoint_label(url),
                    attempt_timeout,
                    attempt,
                    retry_count,
                )
                continue
            raise RuntimeError(
                f"Request timed out calling endpoint={safe_endpoint_label(url)} after {attempt_timeout}s"
            ) from exc
        except URLError as exc:
            last_exc = exc
            if attempt < attempts:
                LOGGER.warning(
                    "Network error calling endpoint=%s, retry %s/%s: %s",
                    safe_endpoint_label(url),
                    attempt,
                    retry_count,
                    exc,
                )
                continue
            raise RuntimeError(f"Network error calling endpoint={safe_endpoint_label(url)}: {exc}") from exc
    else:
        raise RuntimeError(f"Request failed calling endpoint={safe_endpoint_label(url)}: {last_exc}")

    try:
        return json.loads(body) if body else {}
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Invalid JSON response from endpoint={safe_endpoint_label(url)}: {body[:200]}"
        ) from exc


def ensure_list_of_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        text = clean_text(value)
        return [text] if text else []
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            text = clean_text(item)
            if text:
                out.append(text)
        return out
    return []


def read_candidates_file(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError(f"Invalid JSON structure: {path.name}")
    items = data.get("curated_items", data.get("items"))
    if not isinstance(items, list):
        raise RuntimeError(f"Invalid JSON curated_items/items list: {path.name}")
    return data


def find_candidates_json(data_dir: Path, target_date: str) -> tuple[dict[str, Any], Path, bool]:
    expected_file = data_dir / f"{target_date}.json"
    if expected_file.exists():
        return read_candidates_file(expected_file), expected_file, False

    candidates = sorted(data_dir.glob("*.json"), reverse=True)
    if not candidates:
        raise RuntimeError(f"No candidates JSON found in {data_dir}")

    for path in candidates[:FALLBACK_SCAN_DAYS]:
        try:
            return read_candidates_file(path), path, True
        except Exception as exc:
            LOGGER.warning("Skip invalid cached JSON %s: %s", path.name, exc)

    raise RuntimeError(f"No valid cached JSON found in {data_dir}")


def build_prompt_items(items: list[dict[str, Any]], timezone_name: str) -> str:
    lines: list[str] = []
    for idx, item in enumerate(items[:MAX_CANDIDATES_FOR_PROMPT], start=1):
        title = clean_text(item.get("title"))
        summary = truncate_text(item.get("summary", ""), 320)
        source = clean_text(item.get("source", ""))
        published_at = clean_text(item.get("published_at", "")) or "未知"
        link = clean_text(item.get("link", ""))
        language = clean_text(item.get("language", ""))
        region = clean_text(item.get("region", ""))
        source_group = clean_text(item.get("source_group", ""))
        source_type = clean_text(item.get("source_type", ""))
        source_quality = clean_text(item.get("source_quality", ""))
        summary_source = clean_text(item.get("summary_source", ""))
        summary_quality = clean_text(item.get("summary_quality", ""))
        category = clean_text(item.get("category", ""))
        topic_tags = item.get("topic_tags", [])
        tags_text = ", ".join(str(tag) for tag in topic_tags if str(tag).strip()) or "N/A"

        if not title or not link:
            continue

        lines.append(
            f"[{idx}]\n"
            f"标题: {title}\n"
            f"来源: {source}\n"
            f"语言: {language or 'unknown'}\n"
            f"区域: {region or 'unknown'}\n"
            f"分组: {source_group or 'unknown'}\n"
            f"来源类型: {source_type or 'unknown'}\n"
            f"来源质量: {source_quality or 'unknown'}\n"
            f"类别: {category or '其他'}\n"
            f"标签: {tags_text}\n"
            f"发布时间: {published_at} ({timezone_name})\n"
            f"链接: {link}\n"
            f"摘要来源: {summary_source or 'unknown'}\n"
            f"摘要质量: {summary_quality or 'unknown'}\n"
            f"摘要: {summary}\n"
        )

    return "\n".join(lines)


def strip_code_fence(text: str) -> str:
    text = text.strip()
    if not text.startswith("```"):
        return text
    lines = text.splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


def extract_json_object_text(text: str) -> str:
    text = strip_code_fence(text)
    if text.startswith("{") and text.endswith("}"):
        return text
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return text[start : end + 1]
    return text


def parse_litellm_report_json(text: str) -> dict[str, Any]:
    json_text = extract_json_object_text(text)
    try:
        obj = json.loads(json_text)
    except json.JSONDecodeError as exc:
        raise LiteLLMReportParseError("LiteLLM did not return valid JSON report") from exc
    if not isinstance(obj, dict):
        raise LiteLLMReportParseError("LiteLLM JSON root must be an object")
    return obj


def normalize_auto_relevance(value: Any) -> str:
    text = clean_text(value)
    if text in VALID_RELATIONS:
        return text

    lower = text.lower()
    if "直接" in text or "direct" in lower:
        return RELATION_DIRECT
    if "暂无" in text or "无明显" in text or "none" in lower:
        return RELATION_NONE
    return RELATION_INDIRECT


def source_name_from_url(url: str) -> str:
    host = urlparse(url).netloc.strip()
    return host or "来源"


def is_google_news_learning_item(item: dict[str, Any]) -> bool:
    source = clean_text(item.get("source", "")).lower()
    link = clean_text(item.get("link", "")).lower()
    source_type = clean_text(item.get("source_type", "")).lower()
    return source_type == "google_news" or "google news" in source or "news.google.com" in link


def safe_learning_source_name(item: dict[str, Any]) -> str:
    source = clean_text(item.get("source", ""))
    link = clean_text(item.get("link", ""))
    link_l = link.lower()
    mapping = [
        ("developers.openai.com", "OpenAI Developers"),
        ("openai.com", "OpenAI"),
        ("github.com/openai/codex", "OpenAI Codex GitHub"),
        ("github.blog", "GitHub Blog"),
        ("docs.github.com", "GitHub Docs"),
        ("docs.anthropic.com", "Anthropic Docs"),
        ("anthropic.com", "Anthropic"),
        ("docs.cursor.com", "Cursor Docs"),
        ("cursor.com", "Cursor"),
        ("sourcegraph.com", "Sourcegraph"),
        ("jetbrains.com", "JetBrains"),
        ("learn.microsoft.com", "Microsoft Learn"),
        ("microsoft.com", "Microsoft"),
        ("youtube.com", "OpenAI YouTube"),
        ("youtu.be", "OpenAI YouTube"),
    ]
    for needle, label in mapping:
        if needle in link_l:
            return label
    if "google news" in source.lower():
        cleaned = re.sub(r"\s*-\s*Google News\s*$", "", source, flags=re.IGNORECASE).strip()
        if cleaned and cleaned.lower() != "google news" and not cleaned.lower().startswith("google news"):
            return cleaned[:60]
        return source_name_from_url(link)
    return source or source_name_from_url(link)


def is_high_quality_learning_item(item: dict[str, Any]) -> bool:
    source_quality = clean_text(item.get("source_quality", "")).lower()
    source_type = clean_text(item.get("source_type", "")).lower()
    summary_quality = clean_text(item.get("summary_quality", "")).lower()
    if is_google_news_learning_item(item):
        return False
    if summary_quality == "empty":
        return False
    if bool(item.get("is_official_source", False)):
        return True
    if source_quality == "high" and summary_quality in {"high", "medium"} and source_type in {"technical_blog", "official_blog", "official_doc", "github_repo", "official_video"}:
        return True
    return False


def parse_iso_datetime(value: Any, tz: timezone) -> datetime:
    text = clean_text(value)
    if not text:
        return datetime.min.replace(tzinfo=timezone.utc)
    iso = text.replace("Z", "+00:00")
    try:
        dt = datetime.fromisoformat(iso)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(tz)
    except ValueError:
        return datetime.min.replace(tzinfo=timezone.utc)


def normalize_learning_type(raw_type: Any, fallback_item: dict[str, Any] | None = None) -> str:
    text = clean_text(raw_type).lower()
    if not text and fallback_item:
        text = clean_text(fallback_item.get("source_type", "")).lower()

    if "official_video" in text or "官方视频" in text:
        return LEARNING_TYPE_OFFICIAL_VIDEO
    if "youtube" in text or "视频" in text:
        return LEARNING_TYPE_YOUTUBE
    if "official" in text or "doc" in text or "官方" in text or "文档" in text:
        return LEARNING_TYPE_OFFICIAL
    if "technical_blog" in text or "技术博客" in text:
        return LEARNING_TYPE_TECH_BLOG
    if "media_article" in text or "google_news" in text or "新闻" in text:
        return LEARNING_TYPE_NEWS
    if "blog" in text or "博客" in text:
        return LEARNING_TYPE_BLOG
    if "tutorial" in text or "教程" in text:
        return LEARNING_TYPE_TUTORIAL

    if fallback_item:
        link = clean_text(fallback_item.get("link", "")).lower()
        source = clean_text(fallback_item.get("source", "")).lower()
        if "youtube.com" in link or "youtu.be" in link:
            return LEARNING_TYPE_YOUTUBE
        if any(k in link for k in ("openai.com", "developers.openai.com", "platform.openai.com")):
            return LEARNING_TYPE_OFFICIAL
        if "blog" in source:
            return LEARNING_TYPE_BLOG
    return LEARNING_TYPE_TUTORIAL


def learning_priority_bucket(item: dict[str, Any]) -> int:
    link = clean_text(item.get("link", "")).lower()
    source_type = clean_text(item.get("source_type", "")).lower()
    source_quality = clean_text(item.get("source_quality", "")).lower()

    if is_google_news_learning_item(item):
        return -2
    if bool(item.get("is_official_source", False)):
        return 6
    if source_type in {"official_doc", "official_video", "github_repo", "official_blog"}:
        return 6
    if any(host in link for host in ("developers.openai.com", "openai.com/codex", "github.com/openai/codex", "docs.github.com", "github.blog")):
        return 6
    if source_quality == "high":
        return 4
    if source_quality == "medium":
        return 2

    return -1 if source_type in {"media_article", "google_news"} else 0


def learning_relevance_score(item: dict[str, Any]) -> int:
    title = clean_text(item.get("title", ""))
    summary = clean_text(item.get("summary", ""))
    source = clean_text(item.get("source", ""))
    tags = item.get("tags", [])
    tag_text = " ".join(str(tag) for tag in tags if str(tag).strip())
    text = f"{title} {summary} {source} {tag_text}".lower()

    score = 0
    for keyword in LEARNING_CORE_KEYWORDS:
        if keyword in text:
            if keyword in ("codex", "agent", "cli", "mcp", "agents.md"):
                score += 6
            else:
                score += 3

    if "openai" in text:
        score += 2
    if "tutorial" in text or "教程" in text:
        score += 2
    if "best practice" in text or "最佳实践" in text:
        score += 1

    source_quality = clean_text(item.get("source_quality", "")).lower()
    source_type = clean_text(item.get("source_type", "")).lower()
    if bool(item.get("is_official_source", False)):
        score += 8
    if source_quality == "high":
        score += 5
    elif source_quality == "low":
        score -= 10
    if source_type == "google_news" or is_google_news_learning_item(item):
        score -= 12
    if source_type == "media_article":
        score -= 5
    summary_quality = clean_text(item.get("summary_quality", "")).lower()
    if summary_quality == "high":
        score += 4
    elif summary_quality == "medium":
        score += 2
    elif summary_quality == "low":
        score -= 4
    elif summary_quality == "empty":
        score -= 12

    if "chatgpt" in text and "codex" not in text:
        score -= 5
    for keyword in LEARNING_NEGATIVE_KEYWORDS:
        if keyword in text and "codex" not in text:
            score -= 3

    return score


def select_learning_candidate(items: list[dict[str, Any]], tz: timezone) -> dict[str, Any] | None:
    ranked: list[tuple[int, int, datetime, dict[str, Any]]] = []
    for item in items[:MAX_LEARNING_CANDIDATES_FOR_PROMPT]:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        if not title or not link:
            continue
        if not is_high_quality_learning_item(item):
            continue

        relevance = learning_relevance_score(item)
        priority = learning_priority_bucket(item)

        if relevance <= 0:
            continue

        published_dt = parse_iso_datetime(item.get("published_at", ""), tz)
        ranked.append((priority, relevance, published_dt, item))

    if not ranked:
        return None

    ranked.sort(key=lambda x: (x[0], x[1], x[2]), reverse=True)
    return ranked[0][3]


def build_learning_prompt_item(item: dict[str, Any] | None, timezone_name: str) -> str:
    if not item:
        return "今日学习候选为空。"

    title = clean_text(item.get("title", ""))
    summary = truncate_text(item.get("summary", ""), 400)
    source = clean_text(item.get("source", ""))
    source_name = safe_learning_source_name(item)
    source_type = clean_text(item.get("source_type", ""))
    source_quality = clean_text(item.get("source_quality", "")) or "unknown"
    summary_source = clean_text(item.get("summary_source", "")) or "unknown"
    summary_quality = clean_text(item.get("summary_quality", "")) or "unknown"
    is_official = bool(item.get("is_official_source", False))
    language = clean_text(item.get("language", ""))
    region = clean_text(item.get("region", ""))
    published_at = clean_text(item.get("published_at", "")) or "未知"
    link = clean_text(item.get("link", ""))
    tags = item.get("tags", [])
    tags_text = ", ".join(str(tag) for tag in tags if str(tag).strip()) or "N/A"
    concept_hint = clean_text(item.get("concept_hint", "")) or concept_from_learning_item(item)

    return (
        f"标题: {title}\n"
        f"来源: {source_name or source}\n"
        f"类型: {source_type or 'unknown'}\n"
        f"来源质量: {source_quality}\n"
        f"是否官方来源: {'true' if is_official else 'false'}\n"
        f"摘要来源: {summary_source}\n"
        f"摘要质量: {summary_quality}\n"
        f"语言: {language or 'unknown'}\n"
        f"区域: {region or 'unknown'}\n"
        f"发布时间: {published_at} ({timezone_name})\n"
        f"链接: {link}\n"
        f"标签: {tags_text}\n"
        f"建议概念: {concept_hint}\n"
        f"简介: {summary}\n"
    )


def ensure_metadata_note(note: str, has_resource: bool) -> str:
    text = clean_text(note)
    if not has_resource:
        return "今日未发现可用学习资源。"
    if not text:
        return DEFAULT_LEARNING_NOTE
    return text


def normalize_codex_learning(
    value: Any,
    selected_item: dict[str, Any] | None,
    candidate_url_set: set[str],
    url_to_source: dict[str, str],
) -> dict[str, str]:
    raw = value if isinstance(value, dict) else {}
    has_resource = selected_item is not None

    selected_url = normalize_url(clean_text(selected_item.get("link", ""))) if selected_item else ""
    selected_source = safe_learning_source_name(selected_item) if selected_item else ""
    selected_title = clean_text(selected_item.get("title", "")) if selected_item else ""

    if not has_resource:
        concept_payload = concept_payload_for_item(None)
        return {
            "resource_title": DEFAULT_LEARNING_EMPTY_TEXT,
            "resource_type": LEARNING_TYPE_NA,
            "source_name": "",
            "source_url": "",
            **concept_payload,
            "confidence_note": ensure_metadata_note("", has_resource=False),
        }

    source_url_raw = clean_text(
        raw.get("source_url")
        or raw.get("link")
        or selected_url
    )
    source_url = normalize_url(source_url_raw)
    if source_url and source_url not in candidate_url_set and selected_url:
        source_url = selected_url
    if not source_url and selected_url:
        source_url = selected_url

    source_name = clean_text(raw.get("source_name", ""))
    if "google news" in source_name.lower():
        source_name = ""
    if not source_name and source_url:
        source_name = url_to_source.get(source_url, "")
    if "google news" in source_name.lower() and selected_item:
        source_name = safe_learning_source_name(selected_item)
    if not source_name:
        source_name = selected_source or source_name_from_url(source_url)

    resource_title = clean_text(raw.get("resource_title", "")) or selected_title
    if not resource_title and not has_resource:
        resource_title = DEFAULT_LEARNING_EMPTY_TEXT

    resource_type = normalize_learning_type(raw.get("resource_type", ""), selected_item)
    if not has_resource:
        resource_type = LEARNING_TYPE_NA

    concept_payload = concept_payload_for_item(selected_item)
    concept = clean_text(raw.get("concept", "")) or concept_payload["concept"]
    if concept not in CONCEPT_EXPLANATIONS:
        concept = concept_payload["concept"]
    defaults = CONCEPT_EXPLANATIONS.get(concept, CONCEPT_EXPLANATIONS["AI Agent"])
    concept_explanation = clean_text(raw.get("concept_explanation", "")) or defaults["concept_explanation"]
    why_it_matters = clean_text(raw.get("why_it_matters", "")) or defaults["why_it_matters"]
    auto_relevance = clean_text(raw.get("auto_relevance", "")) or defaults["auto_relevance"]
    example_scenario = clean_text(raw.get("example_scenario", "")) or defaults["example_scenario"]
    confidence_note = clean_text(raw.get("confidence_note", ""))

    source_quality = clean_text(selected_item.get("source_quality", "")) if selected_item else ""
    summary_quality = clean_text(selected_item.get("summary_quality", "")) if selected_item else ""
    source_type = clean_text(selected_item.get("source_type", "")) if selected_item else ""
    is_official = bool(selected_item.get("is_official_source", False)) if selected_item else False
    if not confidence_note:
        if summary_quality in {"low", "empty"}:
            confidence_note = "仅基于标题/简短摘要整理，未验证完整正文，建议打开原链接查看。"
        elif is_official and source_quality == "high" and summary_quality == "high" and source_type == "official_doc":
            confidence_note = "基于官方文档摘要整理。"
        elif source_type in {"google_news", "media_article", "official_video"}:
            confidence_note = "基于标题和摘要整理，建议打开原链接查看完整内容。"
        else:
            confidence_note = DEFAULT_LEARNING_NOTE
    confidence_note = ensure_metadata_note(confidence_note, has_resource=True)

    return {
        "resource_title": truncate_text(resource_title, 140),
        "resource_type": truncate_text(resource_type, 30),
        "source_name": truncate_text(source_name or "来源", 60),
        "source_url": source_url,
        "concept": truncate_text(concept, 40),
        "concept_explanation": truncate_text(concept_explanation, 80),
        "why_it_matters": truncate_text(why_it_matters, 100),
        "auto_relevance": truncate_text(auto_relevance, 100),
        "example_scenario": truncate_text(example_scenario, 100),
        "confidence_note": truncate_text(confidence_note, 140),
    }


def tag_texts(item: dict[str, Any]) -> set[str]:
    tags: set[str] = set()
    for key in ("category", "source_group", "source_type"):
        text = clean_text(item.get(key, "")).lower()
        if text:
            tags.add(text)
    for key in ("topic_tags", "tags"):
        values = item.get(key, [])
        if isinstance(values, list):
            for value in values:
                text = clean_text(value).lower()
                if text:
                    tags.add(text)
    return tags


def has_any_tag(tags: set[str], needles: tuple[str, ...]) -> bool:
    return any(any(needle in tag for needle in needles) for tag in tags)


def concept_from_learning_item(item: dict[str, Any] | None) -> str:
    if not item:
        return "AI Agent"
    hint = clean_text(item.get("concept_hint", ""))
    if hint in CONCEPT_EXPLANATIONS:
        return hint
    tags = tag_texts(item)
    for needles, concept in CONCEPT_HINT_RULES:
        if tags & needles:
            return concept
    return "AI Agent"


def concept_payload_for_item(item: dict[str, Any] | None) -> dict[str, str]:
    concept = concept_from_learning_item(item)
    details = CONCEPT_EXPLANATIONS.get(concept, CONCEPT_EXPLANATIONS["AI Agent"])
    return {
        "concept": concept,
        "concept_explanation": details["concept_explanation"],
        "why_it_matters": details["why_it_matters"],
        "auto_relevance": details["auto_relevance"],
        "example_scenario": details["example_scenario"],
    }


def impact_brief_for_item(item: dict[str, Any]) -> str:
    tags = tag_texts(item)
    if has_any_tag(tags, ("agent", "coding", "codex", "mcp", "ai编程工具")):
        return "对汽车软件研发、测试自动化、代码审查、问题定位和研发流程提效有参考价值，但安全关键代码仍需人工审查。"
    if has_any_tag(tags, ("组织提效", "workflow", "automation", "governance", "productivity", "工作流")):
        return "对研发组织的知识管理、需求分析、项目协同、流程自动化和工具推广策略有参考意义。"
    if has_any_tag(tags, ("obc", "dcdc", "车载电源", "power_supply", "电源电子")):
        return "与车载电源电子、OBC、DCDC、电源控制、故障诊断或预测性维护相关，对硬件平台和测试验证有直接参考价值。"
    if has_any_tag(tags, ("power", "sic", "gan", "功率电子", "thermal", "module")):
        return "可能影响 SiC/GaN 功率模块、电源控制、热管理、仿真优化和硬件设计流程。"
    if has_any_tag(tags, ("official", "report", "whitepaper", "research", "白皮书", "技术报告", "官方研究")):
        return "该内容来自官方研究或技术报告，适合作为技术趋势观察，但需要区分研究、参考设计和量产落地。"
    if has_any_tag(tags, ("infrastructure", "chip", "gpu", "accelerator", "ai芯片", "ai基础设施")):
        return "对云端训练、推理基础设施、边缘 AI 或车企研发算力平台有间接参考意义。"
    if has_any_tag(tags, ("自动驾驶", "智能座舱", "autonomous", "cockpit", "adas")):
        return "该内容仅作为汽车智能化补充信息，除非涉及明确 AI 工具链或系统工程变化，否则短期影响有限。"
    return "该动态可作为 AI 技术趋势补充观察，实际影响需要结合具体产品、研发流程和工程约束判断。"


def why_important_for_item(item: dict[str, Any]) -> str:
    tags = [clean_text(tag) for tag in item.get("topic_tags", []) if clean_text(tag)]
    topic_hint = natural_topic_phrase(item)
    if tags:
        return f"该内容涉及{topic_hint}等主题，可用于观察相关技术路线和工具链变化。"
    return f"该内容涉及{topic_hint}，可用于观察相关技术路线、生态变化和潜在工程影响。"


def natural_topic_phrase(item: dict[str, Any]) -> str:
    tags = tag_texts(item)
    phrases: list[str] = []
    if has_any_tag(tags, ("agent", "coding", "codex", "mcp", "ai编程工具")):
        phrases.append("AI Agent 和研发效率")
    if has_any_tag(tags, ("组织提效", "workflow", "automation", "governance", "productivity", "工作流")):
        phrases.append("企业工作流自动化")
    if has_any_tag(tags, ("obc", "dcdc", "车载电源", "power_supply", "电源电子")):
        phrases.append("车载电源电子")
    if has_any_tag(tags, ("power", "sic", "gan", "功率电子", "thermal", "module")):
        phrases.append("功率电子")
    if has_any_tag(tags, ("official", "report", "whitepaper", "research", "白皮书", "技术报告", "官方研究")):
        phrases.append("官方研究与技术报告")
    if has_any_tag(tags, ("infrastructure", "chip", "gpu", "accelerator", "ai芯片", "ai基础设施")):
        phrases.append("AI 基础设施和芯片")
    if has_any_tag(tags, ("自动驾驶", "智能座舱", "autonomous", "cockpit", "adas")):
        phrases.append("汽车智能化")
    return "、".join(phrases[:3]) if phrases else "AI 技术进展"


def summary_topic_tags(item: dict[str, Any]) -> set[str]:
    tags = tag_texts(item)
    for key in ("title", "summary", "what_happened", "why_important", "auto_impact_brief"):
        text = clean_text(item.get(key, "")).lower()
        if text:
            tags.add(text)
    return tags


def dedupe_summary_topics(top_news: list[dict[str, Any]]) -> list[str]:
    topic_rules: list[tuple[str, tuple[str, ...]]] = [
        ("AI Agent 与编程智能体", ("ai agent", "agent", "agentic", "codex", "mcp", "coding_agent", "ai编程工具", "编程智能体")),
        ("研发效率与软件工程提效", ("coding", "developer", "software engineering", "代码", "研发效率", "软件工程", "测试自动化", "代码审查")),
        ("企业 AI 工作流自动化", ("workflow", "automation", "enterprise", "工作流", "流程自动化", "企业 ai", "协同")),
        ("官方研究与技术报告", ("official", "report", "whitepaper", "research", "technical_blog", "官方研究", "技术报告", "白皮书", "官方技术")),
        ("AI 基础设施与云平台", ("infrastructure", "cloud", "aws", "azure", "云平台", "ai基础设施", "算力平台")),
        ("OBC/DCDC 与车载电源电子", ("obc", "dcdc", "车载电源", "电源电子", "电源控制")),
        ("功率电子与 SiC/GaN", ("power_electronics", "功率电子", "sic", "gan", "功率模块")),
        ("AI 芯片与推理基础设施", ("ai芯片", "chip", "gpu", "accelerator", "推理", "inference", "边缘 ai")),
        ("AI 采用治理与组织变革", ("governance", "adoption", "组织提效", "组织变革", "治理", "推广策略")),
        ("汽车软件与系统工程", ("automotive software", "system engineering", "汽车软件", "系统工程", "智能汽车")),
    ]

    topics: list[str] = []
    for item in top_news:
        if not isinstance(item, dict):
            continue
        tags = summary_topic_tags(item)
        for label, needles in topic_rules:
            if label in topics:
                continue
            if has_any_tag(tags, needles):
                topics.append(label)
            if len(topics) >= 3:
                return topics

    return topics[:3] or ["AI 技术与工程应用"]


def join_chinese_list(values: list[str]) -> str:
    cleaned = [clean_text(value) for value in values if clean_text(value)]
    if not cleaned:
        return ""
    if len(cleaned) == 1:
        return cleaned[0]
    if len(cleaned) == 2:
        return f"{cleaned[0]}和{cleaned[1]}"
    return f"{'、'.join(cleaned[:-1])}和{cleaned[-1]}"


def build_rule_based_summary(top_news: list[dict[str, Any]]) -> list[str]:
    if not top_news:
        return ["今日未发现足够高质量的 AI 相关新增内容，暂不生成完整日报。"]

    topics = dedupe_summary_topics(top_news)
    topic_text = join_chinese_list(topics)
    tags = set()
    for item in top_news:
        if isinstance(item, dict):
            tags.update(summary_topic_tags(item))

    has_power = has_any_tag(tags, ("obc", "dcdc", "车载电源", "power_electronics", "功率电子", "sic", "gan"))
    has_agent = has_any_tag(tags, ("ai agent", "agent", "codex", "coding_agent", "ai编程工具", "编程智能体"))
    has_official = has_any_tag(tags, ("official", "report", "whitepaper", "research", "technical_blog", "官方研究", "技术报告", "白皮书"))
    has_infra = has_any_tag(tags, ("infrastructure", "cloud", "aws", "azure", "gpu", "chip", "云平台", "ai基础设施", "推理"))
    has_workflow = has_any_tag(tags, ("workflow", "automation", "productivity", "工作流", "流程自动化", "研发效率", "软件工程"))

    if has_power:
        lines = [f"今日重点关注 {topic_text}相关进展。"]
        lines.append("其中车载电源电子、功率电子或电源控制相关内容，对硬件平台选型、仿真验证和故障诊断有参考价值。")
        if has_agent:
            lines.append("AI Agent 与编程工具方向则更偏向汽车软件研发流程和测试自动化提效。")
        else:
            lines.append("对汽车行业的启发主要集中在系统工程、测试验证和工程工具链演进。")
        return [truncate_text(line, 80) for line in lines[:3]]

    if has_official and len(top_news) <= 3 and not has_agent and not has_workflow:
        lines = [
            "今日入选内容以官方研究、技术报告和工程实践文章为主。",
            "这些内容更适合作为技术趋势观察和方法参考，不宜直接解读为短期量产落地。",
            "对汽车行业的价值主要体现在研发工具链、系统工程和平台技术储备。",
        ]
        return [truncate_text(line, 80) for line in lines]

    lines = [f"今日重点关注 {topic_text}等方向。"]
    if has_workflow or has_infra:
        lines.append("多条内容与企业工具链、软件工程提效和云端基础设施有关。")
    elif has_official:
        lines.append("入选内容以官方技术文章和工程实践为主，适合作为技术趋势观察。")
    else:
        lines.append("入选内容更偏向 AI 技术进展和工程应用线索，适合持续跟踪。")
    lines.append("对汽车行业的启发主要集中在研发流程自动化、测试效率提升和工程工具链演进。")
    return [truncate_text(line, 80) for line in lines[:3]]


def auto_relevance_for_item(item: dict[str, Any]) -> str:
    tags = tag_texts(item)
    if has_any_tag(tags, ("obc", "dcdc", "车载电源", "power", "功率电子")):
        return RELATION_DIRECT
    if has_any_tag(tags, ("自动驾驶", "智能座舱")) and not has_any_tag(tags, ("agent", "coding", "workflow")):
        return RELATION_NONE
    return RELATION_INDIRECT


def build_rule_based_codex_learning(learning_item: dict[str, Any] | None) -> dict[str, str]:
    if not learning_item:
        return normalize_codex_learning(value={}, selected_item=None, candidate_url_set=set(), url_to_source={})

    link = normalize_url(clean_text(learning_item.get("link", "")))
    concept_payload = concept_payload_for_item(learning_item)
    summary_quality = clean_text(learning_item.get("summary_quality", "")).lower()
    source_quality = clean_text(learning_item.get("source_quality", "")).lower()
    source_type = clean_text(learning_item.get("source_type", "")).lower()
    if summary_quality in {"low", "empty"}:
        confidence_note = "仅基于标题/简短摘要整理，未验证完整正文，建议打开原链接查看。"
    elif source_type == "official_doc" and source_quality == "high" and bool(learning_item.get("is_official_source", False)):
        confidence_note = "基于官方文档摘要整理。"
    elif source_type in {"google_news", "media_article", "official_video"}:
        confidence_note = "基于标题和摘要整理，建议打开原链接查看完整内容。"
    else:
        confidence_note = DEFAULT_LEARNING_NOTE

    result = {
        "resource_title": truncate_text(clean_text(learning_item.get("title", "")), 140),
        "resource_type": normalize_learning_type(learning_item.get("source_type", ""), learning_item),
        "source_name": truncate_text(safe_learning_source_name(learning_item), 60),
        "source_url": link,
        "confidence_note": truncate_text(confidence_note, 140),
    }
    result.update(concept_payload)
    return result


def build_rule_based_report(
    news_items: list[dict[str, Any]],
    learning_item: dict[str, Any] | None,
    target_date: str,
) -> dict[str, Any]:
    top_news: list[dict[str, str]] = []
    for item in news_items[:DEFAULT_NEWS_TOP_N]:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        if not title or not link:
            continue
        summary = truncate_text(item.get("summary", ""), 160)
        if not summary:
            summary = "公开摘要为空，需打开原链接核验细节。"
        if clean_text(item.get("summary_quality", "")).lower() == "low":
            summary = f"公开摘要较短：{summary}"
        source = clean_text(item.get("source", "")) or source_name_from_url(link)
        top_news.append(
            {
                "category": clean_text(item.get("category", "")) or "其他",
                "title": title,
                "what_happened": summary,
                "why_important": why_important_for_item(item),
                "auto_relevance": auto_relevance_for_item(item),
                "auto_impact_brief": impact_brief_for_item(item),
                "source_name": source,
                "source_url": normalize_url(link) or link,
            }
        )

    return {
        "title": f"AI 科技日报｜{target_date}",
        "is_rule_based_fallback": True,
        "summary": build_rule_based_summary(top_news),
        "top_news": top_news,
        "codex_learning": build_rule_based_codex_learning(learning_item),
    }


def build_candidate_index(items: list[dict[str, Any]]) -> tuple[set[str], dict[str, str], dict[str, str], dict[str, str]]:
    url_set: set[str] = set()
    title_to_url: dict[str, str] = {}
    url_to_source: dict[str, str] = {}
    url_to_category: dict[str, str] = {}

    for item in items:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        source = clean_text(item.get("source", ""))
        norm_url = normalize_url(link)
        if norm_url:
            url_set.add(norm_url)
            if source:
                url_to_source[norm_url] = source
            category = clean_text(item.get("category", ""))
            if category:
                url_to_category[norm_url] = category
        if title and norm_url:
            title_to_url[title] = norm_url

    return url_set, title_to_url, url_to_source, url_to_category


def normalize_top_news_item(
    value: Any,
    candidate_url_set: set[str],
    title_to_url: dict[str, str],
    url_to_source: dict[str, str],
    url_to_category: dict[str, str],
) -> dict[str, str] | None:
    if not isinstance(value, dict):
        return None

    title = clean_text(value.get("title", ""))
    if not title:
        return None

    source_url_raw = clean_text(
        value.get("source_url")
        or value.get("link")
        or value.get("source_link")
        or value.get("url")
        or ""
    )
    source_url_norm = normalize_url(source_url_raw)

    if not source_url_norm or source_url_norm not in candidate_url_set:
        source_url_norm = title_to_url.get(title, "")

    if not source_url_norm or source_url_norm not in candidate_url_set:
        return None

    source_name = clean_text(value.get("source_name", ""))
    if not source_name:
        source_name = url_to_source.get(source_url_norm, "")
    if not source_name:
        source_name = source_name_from_url(source_url_norm)
    category = clean_text(value.get("category", ""))
    if not category:
        category = url_to_category.get(source_url_norm, "")
    if not category:
        category = "其他"

    return {
        "category": category,
        "title": title,
        "what_happened": clean_text(value.get("what_happened", "")),
        "why_important": clean_text(value.get("why_important", "")),
        "auto_relevance": normalize_auto_relevance(value.get("auto_relevance", "")),
        "auto_impact_brief": clean_text(value.get("auto_impact_brief", "")),
        "source_name": source_name,
        "source_url": source_url_norm,
    }


def build_fallback_news_from_candidates(items: list[dict[str, Any]], news_top_n: int) -> list[dict[str, str]]:
    fallback: list[dict[str, str]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        source = clean_text(item.get("source", "")) or source_name_from_url(link)
        summary = clean_text(item.get("summary", ""))
        if not title or not link:
            continue
        fallback.append(
            {
                "category": clean_text(item.get("category", "")) or "其他",
                "title": title,
                "what_happened": summary or "公开摘要为空，需结合原文核验细节。",
                "why_important": "该新闻反映 AI 技术或产业动态，可能影响车型与研发路线决策。",
                "auto_relevance": RELATION_INDIRECT,
                "auto_impact_brief": "短期主要影响研发优先级与技术评估，量产影响仍需结合平台节奏观察。",
                "source_name": source,
                "source_url": link,
            }
        )
        if len(fallback) >= max(news_top_n, 1):
            break
    return fallback


def is_china_candidate(item: dict[str, Any]) -> bool:
    region = clean_text(item.get("region", "")).lower()
    source_group = clean_text(item.get("source_group", "")).lower()
    language = clean_text(item.get("language", "")).lower()
    return (
        region == "china"
        or source_group in ("china", "auto_china")
        or language == "zh"
    )


def count_china_news(top_news: list[dict[str, str]], china_links: set[str]) -> int:
    count = 0
    for item in top_news:
        link = normalize_url(clean_text(item.get("source_url", "")))
        if link and link in china_links:
            count += 1
    return count


def build_china_fallback_news(items: list[dict[str, Any]], limit: int) -> list[dict[str, str]]:
    fallback: list[dict[str, str]] = []
    for item in items:
        if not isinstance(item, dict) or not is_china_candidate(item):
            continue

        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        source = clean_text(item.get("source", "")) or source_name_from_url(link)
        summary = clean_text(item.get("summary", ""))
        if not title or not link:
            continue

        fallback.append(
            {
                "category": clean_text(item.get("category", "")) or "中国汽车",
                "title": title,
                "what_happened": summary or "公开摘要为空，需结合原文核验细节。",
                "why_important": "该动态与国内 AI/智能汽车产业链相关，可能影响车型规划、技术路线或供应链决策。",
                "auto_relevance": RELATION_INDIRECT,
                "auto_impact_brief": "短期可用于评估国内技术栈与合作生态变化，中长期需结合量产与法规进展持续观察。",
                "source_name": source,
                "source_url": link,
            }
        )
        if len(fallback) >= max(limit, 1):
            break
    return fallback


def normalize_report_payload(
    raw: dict[str, Any],
    report_date: str,
    news_top_n: int,
    candidate_items: list[dict[str, Any]],
    selected_learning_item: dict[str, Any] | None,
    learning_candidate_items: list[dict[str, Any]],
) -> dict[str, Any]:
    title = clean_text(raw.get("title", "")) or f"AI 科技日报｜{report_date}"

    summary = ensure_list_of_strings(raw.get("summary"))[:5]
    if not summary:
        summary = ["新闻内容已整理，但未返回有效摘要。"]

    top_raw = raw.get("top_news")
    if not isinstance(top_raw, list):
        top_raw = []

    candidate_url_set, title_to_url, url_to_source, url_to_category = build_candidate_index(candidate_items)
    top_news: list[dict[str, str]] = []
    for item in top_raw:
        normalized = normalize_top_news_item(
            item,
            candidate_url_set=candidate_url_set,
            title_to_url=title_to_url,
            url_to_source=url_to_source,
            url_to_category=url_to_category,
        )
        if not normalized:
            continue
        top_news.append(normalized)
        if len(top_news) >= max(news_top_n, 1):
            break

    if not top_news:
        top_news = build_fallback_news_from_candidates(candidate_items, news_top_n)

    china_links = {
        normalize_url(clean_text(item.get("link", "")))
        for item in candidate_items
        if isinstance(item, dict) and is_china_candidate(item)
    }
    china_links = {link for link in china_links if link}
    available_china_count = len(china_links)

    desired_china_min = min(2, max(news_top_n, 1), available_china_count)
    if available_china_count > 0 and desired_china_min <= 0:
        desired_china_min = 1

    current_china_count = count_china_news(top_news, china_links)
    if current_china_count < desired_china_min:
        supplements = build_china_fallback_news(candidate_items, desired_china_min - current_china_count)
        existing_links = {normalize_url(clean_text(i.get("source_url", ""))) for i in top_news}
        for candidate in supplements:
            candidate_link = normalize_url(clean_text(candidate.get("source_url", "")))
            if not candidate_link or candidate_link in existing_links:
                continue
            if len(top_news) < max(news_top_n, 1):
                top_news.append(candidate)
            else:
                # Replace the least recent/least specific tail item to keep top N stable.
                top_news[-1] = candidate
            existing_links.add(candidate_link)
            current_china_count += 1
            if current_china_count >= desired_china_min:
                break

    learning_url_set, _, learning_url_to_source, _ = build_candidate_index(learning_candidate_items)
    if selected_learning_item:
        selected_url = normalize_url(clean_text(selected_learning_item.get("link", "")))
        if selected_url:
            learning_url_set.add(selected_url)
            selected_source = clean_text(selected_learning_item.get("source", ""))
            if selected_source:
                learning_url_to_source[selected_url] = selected_source

    codex_learning = normalize_codex_learning(
        value=raw.get("codex_learning"),
        selected_item=selected_learning_item,
        candidate_url_set=learning_url_set,
        url_to_source=learning_url_to_source,
    )

    return {
        "title": title,
        "report_date": report_date,
        "summary": summary,
        "top_news": top_news,
        "codex_learning": codex_learning,
    }


def normalize_title_for_dedupe(title: Any) -> str:
    text = clean_text(title).lower()
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"[^\w\u4e00-\u9fff]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def final_dedupe_top_news(report: dict[str, Any], news_top_n: int) -> dict[str, Any]:
    raw_items = report.get("top_news")
    if not isinstance(raw_items, list):
        report["top_news"] = []
        return report

    deduped: list[dict[str, Any]] = []
    seen_urls: set[str] = set()
    seen_titles: list[str] = []
    seen_source_topics: set[tuple[str, str]] = set()

    for item in raw_items:
        if not isinstance(item, dict):
            continue
        title_key = normalize_title_for_dedupe(item.get("title", ""))
        if not title_key:
            continue
        url_key = normalize_url(clean_text(item.get("source_url", "")))
        if url_key and url_key in seen_urls:
            continue
        if title_key in seen_titles:
            continue
        if any(difflib.SequenceMatcher(None, title_key, old).ratio() >= 0.82 for old in seen_titles):
            continue

        source_key = clean_text(item.get("source_name", "")).lower()
        topic_key = clean_text(item.get("category", "")).lower()
        source_topic_key = (source_key, topic_key)
        if source_key and topic_key and source_topic_key in seen_source_topics:
            continue

        deduped.append(item)
        seen_titles.append(title_key)
        if url_key:
            seen_urls.add(url_key)
        if source_key and topic_key:
            seen_source_topics.add(source_topic_key)
        if len(deduped) >= max(news_top_n, 1):
            break

    report["top_news"] = deduped
    return report


def apply_news_field_limits(report: dict[str, Any], what_max: int, why_max: int, impact_max: int) -> None:
    for item in report.get("top_news", []):
        if not isinstance(item, dict):
            continue
        item["what_happened"] = truncate_text(item.get("what_happened", "") or "仍需观察。", what_max)
        item["why_important"] = truncate_text(item.get("why_important", "") or "仍需观察。", why_max)
        item["auto_impact_brief"] = truncate_text(
            item.get("auto_impact_brief", "") or "对汽车行业的实际影响仍需结合车型与研发节奏观察。",
            impact_max,
        )
        item["title"] = truncate_text(item.get("title", "未命名新闻"), 120)
        item["source_name"] = truncate_text(item.get("source_name", "来源"), 48)


def apply_learning_field_limits(
    report: dict[str, Any],
    learning_point_max: int,
    apply_max: int,
    prompt_max: int,
    note_max: int,
) -> None:
    learning = report.get("codex_learning")
    if not isinstance(learning, dict):
        return

    learning["resource_title"] = truncate_text(learning.get("resource_title", ""), 140)
    learning["resource_type"] = truncate_text(learning.get("resource_type", LEARNING_TYPE_NA), 30)
    learning["source_name"] = truncate_text(learning.get("source_name", "来源"), 60)
    learning["concept"] = truncate_text(learning.get("concept", "AI Agent"), 40)
    learning["concept_explanation"] = truncate_text(learning.get("concept_explanation", ""), 80)
    learning["why_it_matters"] = truncate_text(learning.get("why_it_matters", ""), 100)
    learning["auto_relevance"] = truncate_text(learning.get("auto_relevance", ""), 100)
    learning["example_scenario"] = truncate_text(learning.get("example_scenario", ""), 100)
    learning["confidence_note"] = truncate_text(
        ensure_metadata_note(learning.get("confidence_note", ""), has_resource=bool(clean_text(learning.get("source_url", "")))),
        note_max,
    )


def estimate_report_size(report: dict[str, Any]) -> int:
    parts = [clean_text(report.get("title", ""))]
    for line in ensure_list_of_strings(report.get("summary")):
        parts.append(line)
    for item in report.get("top_news", []):
        if not isinstance(item, dict):
            continue
        parts.extend(
            [
                clean_text(item.get("title", "")),
                clean_text(item.get("what_happened", "")),
                clean_text(item.get("why_important", "")),
                clean_text(item.get("auto_relevance", "")),
                clean_text(item.get("auto_impact_brief", "")),
                clean_text(item.get("source_name", "")),
            ]
        )

    learning = report.get("codex_learning")
    if isinstance(learning, dict):
        parts.extend(
            [
                clean_text(learning.get("resource_title", "")),
                clean_text(learning.get("resource_type", "")),
                clean_text(learning.get("source_name", "")),
                clean_text(learning.get("concept", "")),
                clean_text(learning.get("concept_explanation", "")),
                clean_text(learning.get("why_it_matters", "")),
                clean_text(learning.get("auto_relevance", "")),
                clean_text(learning.get("example_scenario", "")),
                clean_text(learning.get("confidence_note", "")),
            ]
        )
    return len("\n".join(parts))


def shrink_report_for_limit(report: dict[str, Any], news_max_chars: int, news_top_n: int) -> dict[str, Any]:
    compact = json.loads(json.dumps(report, ensure_ascii=False))
    if not isinstance(compact.get("top_news"), list):
        compact["top_news"] = []

    compact["top_news"] = compact["top_news"][: max(news_top_n, 1)]

    profiles = [
        (120, 120, 100),
        (100, 100, 80),
        (90, 90, 70),
        (80, 80, 60),
    ]

    for what_max, why_max, impact_max in profiles:
        apply_news_field_limits(compact, what_max, why_max, impact_max)
        apply_learning_field_limits(compact, 140, 150, 200, 120)
        if estimate_report_size(compact) <= news_max_chars:
            return compact

    summary = ensure_list_of_strings(compact.get("summary"))
    compact["summary"] = [truncate_text(line, 80) for line in summary[:3]]

    while len(compact["top_news"]) > 1 and estimate_report_size(compact) > news_max_chars:
        compact["top_news"].pop()

    apply_news_field_limits(compact, 80, 80, 60)
    apply_learning_field_limits(compact, 120, 120, 180, 110)
    if estimate_report_size(compact) > news_max_chars:
        compact["summary"] = [truncate_text(line, 60) for line in compact.get("summary", [])[:2]]
        apply_news_field_limits(compact, 70, 70, 50)
        apply_learning_field_limits(compact, 100, 100, 140, 90)

    return compact


def create_report_json_with_litellm(
    base_url: str,
    api_key: str,
    model: str,
    report_date: str,
    timezone_name: str,
    news_top_n: int,
    news_max_chars: int,
    items: list[dict[str, Any]],
    source_json_name: str,
    used_fallback_cache: bool,
    selected_learning_item: dict[str, Any] | None,
    learning_items: list[dict[str, Any]],
    learning_source_json_name: str,
    learning_used_fallback_cache: bool,
) -> dict[str, Any]:
    endpoint = base_url.rstrip("/") + "/chat/completions"
    prompt_items = build_prompt_items(items, timezone_name)
    china_candidate_count = sum(
        1 for item in items if isinstance(item, dict) and is_china_candidate(item)
    )
    global_candidate_count = sum(
        1
        for item in items
        if isinstance(item, dict) and not is_china_candidate(item)
    )
    auto_china_candidate_count = sum(
        1
        for item in items
        if isinstance(item, dict)
        and clean_text(item.get("source_group", "")).lower() == "auto_china"
    )
    cache_note = (
        f"目标日期 JSON 缺失，本次使用最近缓存文件 {source_json_name}。"
        if used_fallback_cache
        else "本次使用目标日期候选新闻 JSON。"
    )

    learning_prompt_item = build_learning_prompt_item(selected_learning_item, timezone_name)
    learning_cache_note = (
        f"学习资源使用目标日期 JSON：{learning_source_json_name}。"
        if not learning_used_fallback_cache
        else f"学习资源目标日期 JSON 缺失，本次使用最近缓存：{learning_source_json_name}。"
    )
    learning_source_count = len(learning_items)
    selected_learning_link = (
        normalize_url(clean_text(selected_learning_item.get("link", "")))
        if selected_learning_item
        else ""
    )

    system_prompt = (
        "你是面向智能汽车行业从业者的 AI 科技日报分析助手。"
        "你只能基于候选新闻和给定学习资源元数据生成结论，不得编造候选列表外事实。"
        "你必须只输出一个合法 JSON 对象，不要输出 Markdown、HTML、代码块或解释文字。"
    )

    user_prompt = f"""
请基于候选新闻与学习资源元数据，生成“单条飞书日报”所需 JSON，严格遵守 schema：
{{
  "title": "AI 科技日报｜{report_date}",
  "summary": ["摘要句子1", "摘要句子2", "摘要句子3"],
  "top_news": [
    {{
      "title": "新闻标题",
      "what_happened": "发生了什么",
      "why_important": "为什么重要",
      "auto_relevance": "直接影响 / 间接影响 / 暂无明显影响",
      "auto_impact_brief": "1-2 句话说明对汽车行业、系统工程、硬件、软件、AI 应用、组织提效或 OBC/DCDC 方向的影响",
      "source_name": "来源名称",
      "source_url": "来源链接"
    }}
  ],
  "codex_learning": {{
    "resource_title": "资源标题",
    "resource_type": "官方文档 / 官方视频 / 技术博客 / 教程 / 新闻",
    "source_name": "来源名称",
    "source_url": "资源链接",
    "concept": "Agent 相关概念名称",
    "concept_explanation": "这个概念是什么",
    "why_it_matters": "为什么重要",
    "auto_relevance": "和汽车软件 / 系统工程 / 研发提效 / 工具链的关系",
    "example_scenario": "一个简短应用场景或类比",
    "confidence_note": "基于来源标题/摘要/官方文档整理，说明可信度"
  }}
}}

约束：
1) 只输出 JSON，不要任何多余文字。
2) `summary` 输出 3-5 句中文。
3) 从最多 {min(len(items), 5)} 条候选新闻中选择最终 {news_top_n} 条 Top News；`top_news` 只输出 {news_top_n} 条（有效新闻不足可少于 {news_top_n}，但要在摘要里如实说明）。
4) `what_happened` 控制在 80-120 字。
5) `why_important` 控制在 80-120 字。
6) `auto_impact_brief` 控制在 60-100 字，且只写 1-2 句，不要展开成长篇。
7) `source_url` 必须来自候选新闻链接；不得编造新链接。
8) 不要输出独立“对汽车行业的影响”“关注建议”“来源链接汇总”章节。
9) {cache_note}
10) 候选新闻已经过 RSS 阶段去重、跨天历史去重、弱相关过滤、分类打标和全球/中国平衡筛选；请从这些候选中选择 Top News，不要主动扩展旧闻。
11) 不要把同一事件的不同转载写成多条 Top News；如果两条候选讲的是同一事件，只保留信息更完整、来源更可靠的一条。
12) 不要选入多条来自同一媒体、同一公司、同一发布会的重复内容。
13) Top News 选择优先级：第一 AI Agent / AI 编程工具 / Codex / MCP / Agent workflow；第二 AI 组织变革 / 研发提效 / 软件工程提效 / 工作流自动化；第三 AI + 车载 OBC / DCDC / 功率电子 / 电源控制 / 故障诊断 / 预测性维护 / 数字孪生；第四头部公司官方研究报告 / 技术博客 / 白皮书；第五其他重大 AI 技术新闻；第六自动驾驶 / 智能座舱，仅作为补充。
14) 不要让普通自动驾驶、普通智能座舱新闻占据 Top 3；只有明显体现 AI Agent、组织提效、软件工程、OBC/DCDC 或重大模型/算法/工具链突破时，才可进入 Top 3。
15) 不要选择纯股市、投资、评级、研报、财报视角新闻，除非其中包含明确 AI 技术或车载电源技术进展。
16) curated_items 中可能包含头部公司官方研究报告、技术博客、白皮书；优先选择信息密度高、技术价值高、对 AI Agent / 组织提效 / OBC-DCDC / 汽车软件有启发的内容。
17) 不要编造候选新闻中不存在的事实。
18) 如果来源是官方研究报告或技术博客，请在 `why_important` 说明技术价值，而不是写成普通新闻。
19) 如果是公司白皮书或研究报告，不要夸大为“已经量产”或“已经落地”，除非候选内容明确说明。
20) 对车载 OBC/DCDC 和功率电子相关内容，要区分研究/白皮书、参考设计、芯片或模块发布、量产应用、行业趋势。
21) 今日摘要要求：若候选中有 AI Agent / AI 编程工具 / AI 工作流内容，至少一句总结该趋势；若有 AI 组织提效 / 研发提效内容，至少一句总结该趋势；若有 OBC/DCDC 或功率电子内容，至少一句说明其对车载电源或硬件平台的影响；若有官方研究/技术报告，至少一句说明其技术价值。不要所有摘要都围绕自动驾驶和智能座舱。
22) 只能基于候选的 title 和 summary 生成内容；如果 summary_quality 是 low/empty，不要编造细节。
23) 如果来源是官方研究/技术博客/白皮书，但 summary_quality 是 low/empty，只能说明“该资源可能值得关注”，不要写成确定结论。
24) 不要假装看过完整视频、完整论文或完整白皮书（complete video / full paper / full whitepaper）。
25) 汽车行业相关判断优先结合系统工程、硬件平台、汽车软件、AI 应用、组织提效、OBC/DCDC 与车载电源方向。
26) `top_news` 不要输出 `category` 字段；日报正文不要出现 `[AI编程工具]`、`[AI基础设施]`、`[AI组织提效]`、`[OBC/DCDC]` 这类方括号分类标签。
27) 总长度适合单条飞书消息，目标约 {news_max_chars} 字符。

Agent 概念每日一学约束：
28) `codex_learning` 只基于给定资源元数据（title、summary、summary_source、summary_quality、source、source_type、source_quality、is_official_source、link、tags、concept_hint）整理，不能假装看过完整视频、字幕或正文。
29) 不要输出 `example_prompt`，不要输出可复制 Prompt，不要输出操作步骤，不要写“你应该执行以下步骤”。
30) 优先使用 `concept_hint` 作为 `concept`；没有 concept_hint 时根据 tags/title/summary 映射；仍无法识别时使用 "AI Agent"。
31) 如果资源是 OpenAI Agents SDK，优先解释 Agent Workflow、Tool Calling、Guardrails、Orchestration、Agent Evaluation 或 Observability。
32) 如果资源是 Codex CLI 或 Codex GitHub，优先解释 Coding Agent；如果资源是 AGENTS.md，解释 Agent Instructions；如果资源是 MCP，解释 MCP。
33) 文案像每日科普，不是操作手册；`concept_explanation` 不超过 80 字，`why_it_matters`、`auto_relevance`、`example_scenario` 各不超过 100 字。
34) 如果 summary_quality 是 low，`confidence_note` 必须说明“仅基于标题/简短摘要整理”。如果 summary_quality 是 empty，不要强行生成详细概念延展。
35) 如果资源不是官方来源，或 summary 很短，`confidence_note` 必须写“基于标题和摘要整理，建议打开原链接查看完整内容。”
36) 如果是 official_doc 且 summary_quality=high，`confidence_note` 可写“基于官方文档摘要整理。”
37) 如果存在学习资源候选，`codex_learning.source_url` 必须来自候选资源链接；`source_name` 不要写成 Google News，尽量使用原始来源名称。

候选池概况：
- 中国候选条数：{china_candidate_count}
- 全球候选条数：{global_candidate_count}
- 中国汽车智能化分组候选条数：{auto_china_candidate_count}
- 学习资源候选条数：{learning_source_count}
- {learning_cache_note}

学习资源（最多 1 条，优先官方 Agent 概念文档 / Agents SDK / MCP / Codex 文档）：
{learning_prompt_item}

候选新闻：
{prompt_items}
""".strip()

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": 4096,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    }

    litellm_timeout_seconds = parse_int_env(
        "LLM_TIMEOUT_SECONDS",
        parse_int_env("LITELLM_TIMEOUT_SECONDS", DEFAULT_LLM_TIMEOUT_SECONDS),
    )
    litellm_retry_count = parse_nonnegative_int_env(
        "LLM_MAX_RETRIES",
        parse_nonnegative_int_env("LITELLM_RETRY_COUNT", DEFAULT_LLM_MAX_RETRIES),
    )
    attempts = litellm_retry_count + 1
    last_exc: Exception | None = None
    raw_report: dict[str, Any] | None = None

    for attempt in range(1, attempts + 1):
        try:
            resp = http_post_json(
                endpoint,
                payload,
                headers={"Authorization": f"Bearer {api_key}"},
                timeout_seconds=litellm_timeout_seconds,
                retry_count=0,
            )

            choices = resp.get("choices")
            if not isinstance(choices, list) or not choices:
                raise RuntimeError("LiteLLM response missing choices")

            message = choices[0].get("message", {})
            content = message.get("content")

            if isinstance(content, list):
                text_parts: list[str] = []
                for part in content:
                    if isinstance(part, dict):
                        text_parts.append(str(part.get("text", "")))
                    else:
                        text_parts.append(str(part))
                content = "".join(text_parts)

            content_text = str(content or "").strip()
            if not content_text:
                raise RuntimeError("LiteLLM returned empty content")

            raw_report = parse_litellm_report_json(content_text)
            break
        except (TimeoutError, URLError, HTTPError, json.JSONDecodeError, RuntimeError, LiteLLMReportParseError) as exc:
            last_exc = exc
            if attempt < attempts:
                LOGGER.warning(
                    "LiteLLM attempt %s/%s failed against endpoint=%s: %s",
                    attempt,
                    attempts,
                    safe_endpoint_label(endpoint),
                    exc,
                )
                continue
            raise RuntimeError(f"LiteLLM failed after {attempts} attempt(s): {exc}") from exc

    if raw_report is None:
        raise RuntimeError(f"LiteLLM failed after {attempts} attempt(s): {last_exc}")

    return normalize_report_payload(
        raw=raw_report,
        report_date=report_date,
        news_top_n=news_top_n,
        candidate_items=items,
        selected_learning_item=selected_learning_item,
        learning_candidate_items=learning_items,
    )


def make_card_shell(title: str) -> dict[str, Any]:
    return {
        "config": {
            "enable_forward": True,
            "update_multi": True,
            "wide_screen_mode": True,
        },
        "header": {
            "template": "blue",
            "title": {"tag": "plain_text", "content": title},
        },
        "elements": [],
    }


def add_section_title(elements: list[dict[str, Any]], title: str) -> None:
    elements.append({"tag": "div", "text": {"tag": "plain_text", "content": title}})


def add_markdown(elements: list[dict[str, Any]], content: str) -> None:
    elements.append({"tag": "markdown", "content": content})


def add_button(elements: list[dict[str, Any]], text: str, url: str, btn_type: str = "default") -> None:
    elements.append(
        {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": text},
                    "url": url,
                    "type": btn_type,
                }
            ],
        }
    )


def build_data_source_note(report: dict[str, Any]) -> str:
    news_source = clean_text(report.get("source_json_name", "N/A"))
    news_fallback = bool(report.get("used_fallback_cache", False))
    learning_source = clean_text(report.get("learning_source_json_name", "N/A"))
    learning_fallback = bool(report.get("learning_used_fallback_cache", False))

    news_note = f"新闻源：{news_source}"
    if news_fallback:
        news_note += "（目标日期缺失，已使用最近缓存）"

    learning_note = f"学习源：{learning_source}"
    if learning_fallback:
        learning_note += "（目标日期缺失，已使用最近缓存）"

    return f"{news_note}；{learning_note}"


def top_news_section_title(report: dict[str, Any]) -> str:
    top_n = parse_int_env("NEWS_TOP_N", DEFAULT_NEWS_TOP_N)
    raw = report.get("news_top_n")
    if isinstance(raw, int) and raw > 0:
        top_n = raw
    return f"二、重要新闻 Top {top_n}"


def is_rule_based_fallback_report(report: dict[str, Any]) -> bool:
    return bool(report.get("is_rule_based_fallback", False))


def build_single_interactive_card(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])
    learning = report.get("codex_learning")
    learning = learning if isinstance(learning, dict) else {}
    hide_generated_fields = is_rule_based_fallback_report(report)

    card = make_card_shell(title)
    elements = card["elements"]

    add_section_title(elements, "一、今日摘要")
    add_markdown(elements, "\n".join(f"- {line}" for line in summary[:5]) or "- 暂无摘要")
    elements.append({"tag": "hr"})

    add_section_title(elements, top_news_section_title(report))
    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue

        news_lines = [
            f"**{idx}. {news.get('title', '未命名新闻')}**",
            f"发生了什么：{news.get('what_happened', '仍需观察。')}",
        ]
        if not hide_generated_fields:
            news_lines.extend(
                [
                    f"为什么重要：{news.get('why_important', '仍需观察。')}",
                    f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}",
                    f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}",
                ]
            )
        news_lines.append(f"来源：{news.get('source_name', '来源')}")
        add_markdown(elements, "\n".join(news_lines))

        source_url = clean_text(news.get("source_url", ""))
        if source_url:
            add_button(elements, "查看来源", source_url, btn_type="primary")

        if idx != len(top_news):
            elements.append({"tag": "hr"})

    elements.append({"tag": "hr"})
    add_section_title(elements, "三、Agent 概念每日一学")

    learning_title = clean_text(learning.get("resource_title", DEFAULT_LEARNING_EMPTY_TEXT))
    learning_type = clean_text(learning.get("resource_type", LEARNING_TYPE_NA))
    learning_source_name = clean_text(learning.get("source_name", "来源"))
    learning_source_url = clean_text(learning.get("source_url", ""))
    concept = clean_text(learning.get("concept", "AI Agent"))
    concept_explanation = clean_text(learning.get("concept_explanation", ""))
    why_it_matters = clean_text(learning.get("why_it_matters", ""))
    auto_relevance = clean_text(learning.get("auto_relevance", ""))
    example_scenario = clean_text(learning.get("example_scenario", ""))
    confidence_note = clean_text(learning.get("confidence_note", DEFAULT_LEARNING_NOTE))

    if learning_title == DEFAULT_LEARNING_EMPTY_TEXT and not learning_source_url:
        add_markdown(elements, DEFAULT_LEARNING_EMPTY_TEXT)
    else:
        learning_lines = [
            f"今日概念：{concept}",
            f"一句话解释：{concept_explanation}",
            f"为什么重要：{why_it_matters}",
            f"汽车研发关联：{auto_relevance}",
            f"简单场景：{example_scenario}",
            f"来源：{learning_source_name}",
        ]
        learning_lines.append(f"备注：{confidence_note}")
        add_markdown(elements, "\n".join(learning_lines))
        if learning_source_url:
            add_button(elements, "打开学习资源", learning_source_url, btn_type="default")

    note_text = build_data_source_note(report)
    elements.append({"tag": "note", "elements": [{"tag": "plain_text", "content": note_text}]})

    return card


def build_single_post_payload(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])
    learning = report.get("codex_learning")
    learning = learning if isinstance(learning, dict) else {}
    hide_generated_fields = is_rule_based_fallback_report(report)

    rows: list[list[dict[str, Any]]] = []

    def row_text(text: str) -> list[dict[str, Any]]:
        return [{"tag": "text", "text": text}]

    def row_link(prefix: str, label: str, href: str) -> list[dict[str, Any]]:
        row: list[dict[str, Any]] = []
        if prefix:
            row.append({"tag": "text", "text": prefix})
        row.append({"tag": "a", "text": label, "href": href})
        return row

    rows.append(row_text("一、今日摘要"))
    for line in summary[:5]:
        rows.append(row_text(f"- {line}"))

    rows.append(row_text(top_news_section_title(report)))
    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue
        rows.append(row_text(f"{idx}. {news.get('title', '未命名新闻')}"))
        rows.append(row_text(f"发生了什么：{news.get('what_happened', '仍需观察。')}"))
        if not hide_generated_fields:
            rows.append(row_text(f"为什么重要：{news.get('why_important', '仍需观察。')}"))
            rows.append(row_text(f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}"))
            rows.append(row_text(f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}"))

        source_name = clean_text(news.get("source_name", "来源"))
        source_url = clean_text(news.get("source_url", ""))
        if source_url:
            rows.append(row_link("来源：", source_name or "打开链接", source_url))

    rows.append(row_text("三、Agent 概念每日一学"))
    learning_title = clean_text(learning.get("resource_title", DEFAULT_LEARNING_EMPTY_TEXT))
    learning_type = clean_text(learning.get("resource_type", LEARNING_TYPE_NA))
    learning_source_name = clean_text(learning.get("source_name", "来源"))
    learning_source_url = clean_text(learning.get("source_url", ""))

    if learning_title == DEFAULT_LEARNING_EMPTY_TEXT and not learning_source_url:
        rows.append(row_text(DEFAULT_LEARNING_EMPTY_TEXT))
    else:
        rows.append(row_text(f"今日资源：{learning_title}"))
        rows.append(row_text(f"类型：{learning_type}"))
        rows.append(row_text(f"今日概念：{learning.get('concept', 'AI Agent')}"))
        rows.append(row_text(f"一句话解释：{learning.get('concept_explanation', '')}"))
        rows.append(row_text(f"为什么重要：{learning.get('why_it_matters', '')}"))
        rows.append(row_text(f"汽车研发关联：{learning.get('auto_relevance', '')}"))
        rows.append(row_text(f"简单场景：{learning.get('example_scenario', '')}"))
        rows.append(row_text(f"备注：{learning.get('confidence_note', DEFAULT_LEARNING_NOTE)}"))
        if learning_source_url:
            rows.append(row_link("来源：", learning_source_name or "打开链接", learning_source_url))

    note_text = build_data_source_note(report)
    rows.append(row_text(note_text))

    return {
        "msg_type": "post",
        "content": {
            "post": {
                "zh_cn": {
                    "title": title,
                    "content": rows,
                }
            }
        },
    }


def build_single_text_payload(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])
    learning = report.get("codex_learning")
    learning = learning if isinstance(learning, dict) else {}
    hide_generated_fields = is_rule_based_fallback_report(report)

    lines = [title, "", "一、今日摘要"]
    lines.extend(f"- {line}" for line in summary[:5])
    lines.extend(["", top_news_section_title(report)])

    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue
        lines.append(f"{idx}. {news.get('title', '未命名新闻')}")
        lines.append(f"发生了什么：{news.get('what_happened', '仍需观察。')}")
        if not hide_generated_fields:
            lines.append(f"为什么重要：{news.get('why_important', '仍需观察。')}")
            lines.append(f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}")
            lines.append(f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}")
        lines.append(f"来源：{news.get('source_name', '来源')} {news.get('source_url', '')}")
        lines.append("")

    lines.extend(["三、Agent 概念每日一学"])
    learning_title = clean_text(learning.get("resource_title", DEFAULT_LEARNING_EMPTY_TEXT))
    learning_source_url = clean_text(learning.get("source_url", ""))
    if learning_title == DEFAULT_LEARNING_EMPTY_TEXT and not learning_source_url:
        lines.append(DEFAULT_LEARNING_EMPTY_TEXT)
    else:
        lines.append(f"今日资源：{learning_title}")
        lines.append(f"类型：{learning.get('resource_type', LEARNING_TYPE_NA)}")
        lines.append(f"今日概念：{learning.get('concept', 'AI Agent')}")
        lines.append(f"一句话解释：{learning.get('concept_explanation', '')}")
        lines.append(f"为什么重要：{learning.get('why_it_matters', '')}")
        lines.append(f"汽车研发关联：{learning.get('auto_relevance', '')}")
        lines.append(f"简单场景：{learning.get('example_scenario', '')}")
        lines.append(f"来源：{learning.get('source_name', '来源')} {learning_source_url}")
        lines.append(f"备注：{learning.get('confidence_note', DEFAULT_LEARNING_NOTE)}")

    note_text = build_data_source_note(report)
    lines.append(note_text)

    return {
        "msg_type": "text",
        "content": {"text": "\n".join(lines).strip()},
    }


def feishu_sign(secret: str) -> tuple[str, str]:
    timestamp = str(int(time.time()))
    string_to_sign = f"{timestamp}\n{secret}"
    hmac_code = hmac.new(
        string_to_sign.encode("utf-8"),
        b"",
        digestmod=hashlib.sha256,
    ).digest()
    sign = base64.b64encode(hmac_code).decode("utf-8")
    return timestamp, sign


def send_feishu_payload(webhook_url: str, payload: dict[str, Any], secret: str | None = None) -> None:
    secret_value = (secret or "").strip()
    send_payload = dict(payload)

    if secret_value:
        timestamp, sign = feishu_sign(secret_value)
        send_payload["timestamp"] = timestamp
        send_payload["sign"] = sign

    resp = http_post_json(webhook_url, send_payload)
    if isinstance(resp, dict) and resp.get("code", 0) != 0:
        raise RuntimeError(f"Feishu error code={resp.get('code')} msg={resp.get('msg')}")


def send_report_with_fallback(webhook_url: str, secret: str | None, report: dict[str, Any]) -> None:
    source_json_name = clean_text(report.get("source_json_name", ""))
    used_fallback_cache = bool(report.get("used_fallback_cache", False))

    interactive_payload = {
        "msg_type": "interactive",
        "card": build_single_interactive_card(
            report=report,
            source_json_name=source_json_name,
            used_fallback_cache=used_fallback_cache,
        ),
    }

    try:
        LOGGER.info("Sending one Feishu interactive card")
        send_feishu_payload(webhook_url, interactive_payload, secret=secret)
        return
    except Exception as exc:
        LOGGER.warning("Interactive card send failed, fallback to post. reason=%s", exc)

    post_payload = build_single_post_payload(
        report=report,
        source_json_name=source_json_name,
        used_fallback_cache=used_fallback_cache,
    )

    try:
        LOGGER.info("Sending one Feishu post message")
        send_feishu_payload(webhook_url, post_payload, secret=secret)
        return
    except Exception as exc:
        LOGGER.warning("Post message send failed, fallback to text. reason=%s", exc)

    text_payload = build_single_text_payload(
        report=report,
        source_json_name=source_json_name,
        used_fallback_cache=used_fallback_cache,
    )
    LOGGER.info("Sending one Feishu text message")
    send_feishu_payload(webhook_url, text_payload, secret=secret)


def build_error_report(report_date: str, detail: str) -> dict[str, Any]:
    return {
        "title": f"AI 科技日报｜{report_date}",
        "report_date": report_date,
        "summary": [f"日报生成失败：{truncate_text(detail, 180)}"],
        "top_news": [],
        "codex_learning": {
            "resource_title": DEFAULT_LEARNING_EMPTY_TEXT,
            "resource_type": LEARNING_TYPE_NA,
            "source_name": "",
            "source_url": "",
            **concept_payload_for_item(None),
            "confidence_note": "今日未发现可用学习资源。",
        },
    }


def select_news_items_for_llm(candidates_payload: dict[str, Any], max_items_for_llm: int) -> tuple[list[dict[str, Any]], str]:
    curated_items = candidates_payload.get("curated_items", [])
    if isinstance(curated_items, list) and curated_items:
        return [item for item in curated_items if isinstance(item, dict)][:max_items_for_llm], "curated_items"

    raw_items = candidates_payload.get("items", [])
    if isinstance(raw_items, list):
        return [item for item in raw_items if isinstance(item, dict)][:max_items_for_llm], "items"
    return [], "none"


def select_learning_items_for_report(learning_payload: dict[str, Any]) -> tuple[list[dict[str, Any]], str]:
    curated_items = learning_payload.get("curated_items", [])
    if isinstance(curated_items, list) and curated_items:
        return [item for item in curated_items if isinstance(item, dict)], "curated_items"

    raw_items = learning_payload.get("items", [])
    if isinstance(raw_items, list):
        return [item for item in raw_items if isinstance(item, dict)], "items"
    return [], "none"


def build_no_significant_news_report(report_date: str, source_name: str, learning_item: dict[str, Any] | None) -> dict[str, Any]:
    learning = normalize_codex_learning(
        value={},
        selected_item=learning_item,
        candidate_url_set={normalize_url(clean_text(learning_item.get("link", "")))} if learning_item else set(),
        url_to_source={normalize_url(clean_text(learning_item.get("link", ""))): clean_text(learning_item.get("source", ""))} if learning_item else {},
    )
    return {
        "title": f"AI 科技日报｜{report_date}",
        "report_date": report_date,
        "summary": [
            "今日未发现足够高质量的 AI 相关新增内容，暂不生成完整日报。",
            "可继续关注 AI Agent、研发效率、车载电源电子和云端基础设施等方向的后续进展。",
        ],
        "top_news": [],
        "codex_learning": learning,
    }


def main() -> int:
    setup_logging()
    project_root = Path(__file__).resolve().parents[1]
    load_dotenv_file(project_root / ".env")

    timezone_name = os.getenv("TIMEZONE", DEFAULT_TIMEZONE)
    news_max_chars = parse_int_env("NEWS_MAX_CHARS", DEFAULT_NEWS_MAX_CHARS)
    news_top_n = parse_int_env("NEWS_TOP_N", DEFAULT_NEWS_TOP_N)
    max_items_for_llm = parse_int_env("MAX_ITEMS_FOR_LLM", DEFAULT_MAX_ITEMS_FOR_LLM)
    llm_provider = os.getenv("LLM_PROVIDER", DEFAULT_LLM_PROVIDER).strip().lower() or DEFAULT_LLM_PROVIDER
    enable_rule_based_fallback = parse_bool_env(
        "ENABLE_RULE_BASED_FALLBACK",
        DEFAULT_ENABLE_RULE_BASED_FALLBACK,
    )

    tz = get_timezone(timezone_name)
    now_local = datetime.now(tz)
    report_date = (now_local - timedelta(days=1)).date().isoformat()

    webhook_url = os.getenv("FEISHU_WEBHOOK_URL", "").strip()
    if not webhook_url:
        raise RuntimeError("Missing FEISHU_WEBHOOK_URL")
    feishu_secret = os.getenv("FEISHU_BOT_SECRET")

    data_dir = project_root / "data" / "news-candidates"
    if not data_dir.exists():
        error_report = build_error_report(report_date, f"目录不存在：{data_dir.as_posix()}")
        error_report["source_json_name"] = "N/A"
        error_report["used_fallback_cache"] = False
        error_report["learning_source_json_name"] = "N/A"
        error_report["learning_used_fallback_cache"] = False
        send_report_with_fallback(webhook_url, feishu_secret, error_report)
        return 1

    try:
        candidates_payload, source_file, used_fallback_cache = find_candidates_json(data_dir, report_date)
    except Exception as exc:
        LOGGER.info(
            "No fresh news candidates JSON for %s; skip Feishu push silently. detail=%s",
            report_date,
            exc,
        )
        return 0

    if used_fallback_cache:
        LOGGER.info(
            "Fresh news candidates JSON %s.json not found; latest available is %s. Skip Feishu push silently.",
            report_date,
            source_file.name,
        )
        return 0

    items, items_field = select_news_items_for_llm(candidates_payload, max_items_for_llm)

    learning_data_dir = project_root / "data" / "learning-candidates"
    learning_items: list[dict[str, Any]] = []
    learning_source_json_name = "N/A"
    learning_used_fallback_cache = False

    if learning_data_dir.exists():
        try:
            learning_payload, learning_source_file, learning_used_fallback_cache = find_candidates_json(
                learning_data_dir,
                report_date,
            )
            learning_source_json_name = learning_source_file.name
            learning_items, learning_items_field = select_learning_items_for_report(learning_payload)
            LOGGER.info(
                "Loaded learning candidates from %s (%s=%s, fallback_cache=%s)",
                learning_source_file.name,
                learning_items_field,
                len(learning_items),
                learning_used_fallback_cache,
            )
        except Exception as exc:
            LOGGER.warning("Load learning candidates failed: %s", exc)
    else:
        LOGGER.warning("Learning candidates directory not found: %s", learning_data_dir.as_posix())

    selected_learning_item = select_learning_candidate(learning_items, tz)
    if selected_learning_item:
        LOGGER.info(
            "Selected learning resource: %s",
            truncate_text(selected_learning_item.get("title", ""), 100),
        )
    else:
        LOGGER.info("No suitable learning resource selected for today")

    if not items:
        empty_report = build_no_significant_news_report(report_date, source_file.name, selected_learning_item)
        empty_report["source_json_name"] = source_file.name
        empty_report["used_fallback_cache"] = used_fallback_cache
        empty_report["learning_source_json_name"] = learning_source_json_name
        empty_report["learning_used_fallback_cache"] = learning_used_fallback_cache
        send_report_with_fallback(webhook_url, feishu_secret, empty_report)
        return 0

    report: dict[str, Any] | None = None
    used_rule_based_report = False
    if llm_provider == "litellm":
        api_key = os.getenv("LITELLM_API_KEY") or os.getenv("OPENAI_API_KEY")
        base_url = os.getenv("LITELLM_BASE_URL", "").strip()
        model = os.getenv("LITELLM_MODEL", "gpt-5.4").strip() or "gpt-5.4"

        LOGGER.info(
            "Generating report JSON from %s (%s=%s, fallback_cache=%s, learning_items=%s)",
            source_file.name,
            items_field,
            len(items),
            used_fallback_cache,
            len(learning_items),
        )

        if not api_key or not base_url:
            message = "Missing LiteLLM API key or base URL"
            if not enable_rule_based_fallback:
                raise RuntimeError(message)
            LOGGER.warning("%s; use rule-based fallback", message)
        else:
            try:
                report = create_report_json_with_litellm(
                    base_url=base_url,
                    api_key=api_key,
                    model=model,
                    report_date=report_date,
                    timezone_name=timezone_name,
                    news_top_n=news_top_n,
                    news_max_chars=news_max_chars,
                    items=items,
                    source_json_name=source_file.name,
                    used_fallback_cache=used_fallback_cache,
                    selected_learning_item=selected_learning_item,
                    learning_items=learning_items,
                    learning_source_json_name=learning_source_json_name,
                    learning_used_fallback_cache=learning_used_fallback_cache,
                )
            except (TimeoutError, URLError, HTTPError, json.JSONDecodeError, RuntimeError, LiteLLMReportParseError) as exc:
                if not enable_rule_based_fallback:
                    raise
                LOGGER.warning(
                    "LiteLLM report generation failed; use rule-based fallback. reason=%s",
                    exc,
                )
    else:
        if not enable_rule_based_fallback:
            raise RuntimeError(f"Unsupported LLM_PROVIDER: {llm_provider}")
        LOGGER.warning("Unsupported LLM_PROVIDER=%s; use rule-based fallback", llm_provider)

    if report is None:
        report = build_rule_based_report(
            news_items=items[:news_top_n],
            learning_item=selected_learning_item,
            target_date=report_date,
        )
        used_rule_based_report = True

    report = normalize_report_payload(
        raw=report,
        report_date=report_date,
        news_top_n=news_top_n,
        candidate_items=items,
        selected_learning_item=selected_learning_item,
        learning_candidate_items=learning_items,
    )
    report = final_dedupe_top_news(report, news_top_n)
    if used_rule_based_report:
        report["is_rule_based_fallback"] = True
        report["summary"] = build_rule_based_summary(report.get("top_news", []))
    report = shrink_report_for_limit(report, news_max_chars, news_top_n)
    report["news_top_n"] = news_top_n
    report["source_json_name"] = source_file.name
    report["used_fallback_cache"] = used_fallback_cache
    report["learning_source_json_name"] = learning_source_json_name
    report["learning_used_fallback_cache"] = learning_used_fallback_cache

    send_report_with_fallback(webhook_url=webhook_url, secret=feishu_secret, report=report)
    LOGGER.info("Daily report sent successfully")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        LOGGER.error("Run failed: %s", exc)
        raise SystemExit(1)
