#!/usr/bin/env python3
"""Generate daily AI news report from cached JSON and push to Feishu.

Hybrid architecture (local stage only):
- Read candidate news JSON generated by GitHub Actions.
- Call LiteLLM via company gateway to produce one compact JSON report.
- Send exactly one Feishu message (interactive card, fallback post, fallback text).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import re
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


LOGGER = logging.getLogger("daily_ai_news")

HTTP_TIMEOUT_SECONDS = 25
MAX_CANDIDATES_FOR_PROMPT = 24
FALLBACK_SCAN_DAYS = 14

DEFAULT_TIMEZONE = "Asia/Shanghai"
DEFAULT_NEWS_MAX_CHARS = 3500
DEFAULT_NEWS_TOP_N = 5

RELATION_DIRECT = "直接影响"
RELATION_INDIRECT = "间接影响"
RELATION_NONE = "暂无明显影响"
VALID_RELATIONS = {RELATION_DIRECT, RELATION_INDIRECT, RELATION_NONE}


class LiteLLMReportParseError(RuntimeError):
    """Raised when LiteLLM content cannot be parsed into expected report JSON."""


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def load_dotenv_file(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if value.startswith(("'", '"')) and value.endswith(("'", '"')) and len(value) >= 2:
            value = value[1:-1]
        os.environ.setdefault(key, value)


def parse_int_env(name: str, default: int) -> int:
    raw = os.getenv(name, str(default)).strip()
    try:
        value = int(raw)
        if value <= 0:
            raise ValueError
        return value
    except ValueError:
        LOGGER.warning("%s invalid (%s), fallback to %s", name, raw, default)
        return default


def get_timezone(tz_name: str) -> timezone:
    try:
        return ZoneInfo(tz_name)
    except ZoneInfoNotFoundError:
        if tz_name == DEFAULT_TIMEZONE:
            return timezone(timedelta(hours=8), name=tz_name)
        if tz_name.upper() == "UTC":
            return timezone.utc
        raise RuntimeError(f"Invalid TIMEZONE: {tz_name}")


def safe_endpoint_label(url: str) -> str:
    parsed = urlparse(url)
    return parsed.netloc or "unknown-host"


def normalize_url(url: str) -> str:
    value = (url or "").strip()
    if not value:
        return ""
    return value.rstrip("/")


def clean_text(value: Any) -> str:
    text = str(value or "")
    text = text.replace("\r", "\n")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def truncate_text(text: str, max_len: int) -> str:
    text = clean_text(text)
    if max_len <= 0:
        return ""
    if len(text) <= max_len:
        return text
    if max_len == 1:
        return text[:1]
    return text[: max_len - 1].rstrip() + "…"


def http_post_json(url: str, payload: dict[str, Any], headers: dict[str, str] | None = None) -> dict[str, Any]:
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req_headers = {"Content-Type": "application/json"}
    if headers:
        req_headers.update(headers)

    request = Request(url=url, data=data, headers=req_headers, method="POST")
    try:
        with urlopen(request, timeout=HTTP_TIMEOUT_SECONDS) as response:
            body = response.read().decode("utf-8", errors="replace")
    except HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
        raise RuntimeError(
            f"HTTP {exc.code} calling endpoint={safe_endpoint_label(url)}: {body[:200]}"
        ) from exc
    except URLError as exc:
        raise RuntimeError(f"Network error calling endpoint={safe_endpoint_label(url)}: {exc}") from exc

    try:
        return json.loads(body) if body else {}
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Invalid JSON response from endpoint={safe_endpoint_label(url)}: {body[:200]}"
        ) from exc


def ensure_list_of_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        text = clean_text(value)
        return [text] if text else []
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            text = clean_text(item)
            if text:
                out.append(text)
        return out
    return []


def read_candidates_file(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError(f"Invalid JSON structure: {path.name}")
    items = data.get("items")
    if not isinstance(items, list):
        raise RuntimeError(f"Invalid JSON items list: {path.name}")
    return data


def find_candidates_json(data_dir: Path, target_date: str) -> tuple[dict[str, Any], Path, bool]:
    expected_file = data_dir / f"{target_date}.json"
    if expected_file.exists():
        return read_candidates_file(expected_file), expected_file, False

    candidates = sorted(data_dir.glob("*.json"), reverse=True)
    if not candidates:
        raise RuntimeError(f"No candidates JSON found in {data_dir}")

    for path in candidates[:FALLBACK_SCAN_DAYS]:
        try:
            return read_candidates_file(path), path, True
        except Exception as exc:
            LOGGER.warning("Skip invalid cached JSON %s: %s", path.name, exc)

    raise RuntimeError(f"No valid cached JSON found in {data_dir}")


def build_prompt_items(items: list[dict[str, Any]], timezone_name: str) -> str:
    lines: list[str] = []
    for idx, item in enumerate(items[:MAX_CANDIDATES_FOR_PROMPT], start=1):
        title = clean_text(item.get("title"))
        summary = truncate_text(item.get("summary", ""), 320)
        source = clean_text(item.get("source", ""))
        published_at = clean_text(item.get("published_at", "")) or "未知"
        link = clean_text(item.get("link", ""))

        if not title or not link:
            continue

        lines.append(
            f"[{idx}]\n"
            f"标题: {title}\n"
            f"来源: {source}\n"
            f"发布时间: {published_at} ({timezone_name})\n"
            f"链接: {link}\n"
            f"摘要: {summary}\n"
        )

    return "\n".join(lines)


def strip_code_fence(text: str) -> str:
    text = text.strip()
    if not text.startswith("```"):
        return text
    lines = text.splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]
    return "\n".join(lines).strip()


def extract_json_object_text(text: str) -> str:
    text = strip_code_fence(text)
    if text.startswith("{") and text.endswith("}"):
        return text
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        return text[start : end + 1]
    return text


def parse_litellm_report_json(text: str) -> dict[str, Any]:
    json_text = extract_json_object_text(text)
    try:
        obj = json.loads(json_text)
    except json.JSONDecodeError as exc:
        raise LiteLLMReportParseError("LiteLLM did not return valid JSON report") from exc
    if not isinstance(obj, dict):
        raise LiteLLMReportParseError("LiteLLM JSON root must be an object")
    return obj


def normalize_auto_relevance(value: Any) -> str:
    text = clean_text(value)
    if text in VALID_RELATIONS:
        return text

    lower = text.lower()
    if "直接" in text or "direct" in lower:
        return RELATION_DIRECT
    if "暂无" in text or "无明显" in text or "none" in lower:
        return RELATION_NONE
    return RELATION_INDIRECT


def source_name_from_url(url: str) -> str:
    host = urlparse(url).netloc.strip()
    return host or "来源"


def build_candidate_index(items: list[dict[str, Any]]) -> tuple[set[str], dict[str, str], dict[str, str]]:
    url_set: set[str] = set()
    title_to_url: dict[str, str] = {}
    url_to_source: dict[str, str] = {}

    for item in items:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        source = clean_text(item.get("source", ""))
        norm_url = normalize_url(link)
        if norm_url:
            url_set.add(norm_url)
            if source:
                url_to_source[norm_url] = source
        if title and norm_url:
            title_to_url[title] = norm_url

    return url_set, title_to_url, url_to_source


def normalize_top_news_item(
    value: Any,
    candidate_url_set: set[str],
    title_to_url: dict[str, str],
    url_to_source: dict[str, str],
) -> dict[str, str] | None:
    if not isinstance(value, dict):
        return None

    title = clean_text(value.get("title", ""))
    if not title:
        return None

    source_url_raw = clean_text(
        value.get("source_url")
        or value.get("link")
        or value.get("source_link")
        or value.get("url")
        or ""
    )
    source_url_norm = normalize_url(source_url_raw)

    if not source_url_norm or source_url_norm not in candidate_url_set:
        source_url_norm = title_to_url.get(title, "")

    if not source_url_norm or source_url_norm not in candidate_url_set:
        return None

    source_name = clean_text(value.get("source_name", ""))
    if not source_name:
        source_name = url_to_source.get(source_url_norm, "")
    if not source_name:
        source_name = source_name_from_url(source_url_norm)

    return {
        "title": title,
        "what_happened": clean_text(value.get("what_happened", "")),
        "why_important": clean_text(value.get("why_important", "")),
        "auto_relevance": normalize_auto_relevance(value.get("auto_relevance", "")),
        "auto_impact_brief": clean_text(value.get("auto_impact_brief", "")),
        "source_name": source_name,
        "source_url": source_url_norm,
    }


def build_fallback_news_from_candidates(items: list[dict[str, Any]], news_top_n: int) -> list[dict[str, str]]:
    fallback: list[dict[str, str]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        title = clean_text(item.get("title", ""))
        link = clean_text(item.get("link", ""))
        source = clean_text(item.get("source", "")) or source_name_from_url(link)
        summary = clean_text(item.get("summary", ""))
        if not title or not link:
            continue
        fallback.append(
            {
                "title": title,
                "what_happened": summary or "候选新闻已抓取，需结合原文核验细节。",
                "why_important": "该新闻反映 AI 技术或产业动态，可能影响车型与研发路线决策。",
                "auto_relevance": RELATION_INDIRECT,
                "auto_impact_brief": "短期主要影响研发优先级与技术评估，量产影响仍需结合平台节奏观察。",
                "source_name": source,
                "source_url": link,
            }
        )
        if len(fallback) >= max(news_top_n, 1):
            break
    return fallback


def normalize_report_payload(
    raw: dict[str, Any],
    report_date: str,
    news_top_n: int,
    candidate_items: list[dict[str, Any]],
) -> dict[str, Any]:
    title = clean_text(raw.get("title", "")) or f"AI 科技日报｜{report_date}"

    summary = ensure_list_of_strings(raw.get("summary"))[:5]
    if not summary:
        summary = ["候选新闻已生成，但模型未返回有效摘要。"]

    top_raw = raw.get("top_news")
    if not isinstance(top_raw, list):
        top_raw = []

    candidate_url_set, title_to_url, url_to_source = build_candidate_index(candidate_items)
    top_news: list[dict[str, str]] = []
    for item in top_raw:
        normalized = normalize_top_news_item(
            item,
            candidate_url_set=candidate_url_set,
            title_to_url=title_to_url,
            url_to_source=url_to_source,
        )
        if not normalized:
            continue
        top_news.append(normalized)
        if len(top_news) >= max(news_top_n, 1):
            break

    if not top_news:
        top_news = build_fallback_news_from_candidates(candidate_items, news_top_n)

    return {
        "title": title,
        "report_date": report_date,
        "summary": summary,
        "top_news": top_news,
    }


def apply_news_field_limits(report: dict[str, Any], what_max: int, why_max: int, impact_max: int) -> None:
    for item in report.get("top_news", []):
        if not isinstance(item, dict):
            continue
        item["what_happened"] = truncate_text(item.get("what_happened", "") or "仍需观察。", what_max)
        item["why_important"] = truncate_text(item.get("why_important", "") or "仍需观察。", why_max)
        item["auto_impact_brief"] = truncate_text(
            item.get("auto_impact_brief", "") or "对汽车行业的实际影响仍需结合车型与研发节奏观察。",
            impact_max,
        )
        item["title"] = truncate_text(item.get("title", "未命名新闻"), 120)
        item["source_name"] = truncate_text(item.get("source_name", "来源"), 48)


def estimate_report_size(report: dict[str, Any]) -> int:
    parts = [clean_text(report.get("title", ""))]
    for line in ensure_list_of_strings(report.get("summary")):
        parts.append(line)
    for item in report.get("top_news", []):
        if not isinstance(item, dict):
            continue
        parts.extend(
            [
                clean_text(item.get("title", "")),
                clean_text(item.get("what_happened", "")),
                clean_text(item.get("why_important", "")),
                clean_text(item.get("auto_relevance", "")),
                clean_text(item.get("auto_impact_brief", "")),
                clean_text(item.get("source_name", "")),
            ]
        )
    return len("\n".join(parts))


def shrink_report_for_limit(report: dict[str, Any], news_max_chars: int, news_top_n: int) -> dict[str, Any]:
    compact = json.loads(json.dumps(report, ensure_ascii=False))
    if not isinstance(compact.get("top_news"), list):
        compact["top_news"] = []

    compact["top_news"] = compact["top_news"][: max(news_top_n, 1)]

    profiles = [
        (120, 120, 100),
        (100, 100, 80),
        (90, 90, 70),
        (80, 80, 60),
    ]

    for what_max, why_max, impact_max in profiles:
        apply_news_field_limits(compact, what_max, why_max, impact_max)
        if estimate_report_size(compact) <= news_max_chars:
            return compact

    summary = ensure_list_of_strings(compact.get("summary"))
    compact["summary"] = [truncate_text(line, 80) for line in summary[:3]]

    while len(compact["top_news"]) > 1 and estimate_report_size(compact) > news_max_chars:
        compact["top_news"].pop()

    apply_news_field_limits(compact, 80, 80, 60)
    if estimate_report_size(compact) > news_max_chars:
        compact["summary"] = [truncate_text(line, 60) for line in compact.get("summary", [])[:2]]
        apply_news_field_limits(compact, 70, 70, 50)

    return compact


def create_report_json_with_litellm(
    base_url: str,
    api_key: str,
    model: str,
    report_date: str,
    timezone_name: str,
    news_top_n: int,
    news_max_chars: int,
    items: list[dict[str, Any]],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    endpoint = base_url.rstrip("/") + "/chat/completions"
    prompt_items = build_prompt_items(items, timezone_name)
    cache_note = (
        f"目标日期 JSON 缺失，本次使用最近缓存文件 {source_json_name}。"
        if used_fallback_cache
        else "本次使用目标日期候选新闻 JSON。"
    )

    system_prompt = (
        "你是面向智能汽车行业从业者的 AI 科技日报分析助手。"
        "你只能基于候选新闻生成结论，不得编造候选列表外事实。"
        "你必须只输出一个合法 JSON 对象，不要输出 Markdown、HTML、代码块或解释文字。"
    )

    user_prompt = f"""
请基于候选新闻生成“单条飞书日报”所需 JSON，严格遵守 schema：
{{
  "title": "AI 科技日报｜{report_date}",
  "summary": ["摘要句子1", "摘要句子2", "摘要句子3"],
  "top_news": [
    {{
      "title": "新闻标题",
      "what_happened": "发生了什么",
      "why_important": "为什么重要",
      "auto_relevance": "直接影响 / 间接影响 / 暂无明显影响",
      "auto_impact_brief": "1-2 句话的简短汽车影响",
      "source_name": "来源名称",
      "source_url": "来源链接"
    }}
  ]
}}

约束：
1) 只输出 JSON，不要任何多余文字。
2) `summary` 输出 3-5 句中文。
3) `top_news` 优先输出 {news_top_n} 条（不足可少于 {news_top_n}，但要在摘要里如实说明）。
4) `what_happened` 控制在 80-120 字。
5) `why_important` 控制在 80-120 字。
6) `auto_impact_brief` 控制在 60-100 字，且只写 1-2 句，不要展开成系统工程/硬件/软件/AI应用四个小节。
7) `source_url` 必须来自候选新闻链接；不得编造新链接。
8) 不要输出独立“对汽车行业的影响”章节。
9) 不要输出独立“对我的关注建议”章节。
10) 不要输出独立“来源链接汇总”章节。
11) {cache_note}
12) 最终内容应适合单条飞书消息阅读，目标总长度约 {news_max_chars} 字符。

候选新闻：
{prompt_items}
""".strip()

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "max_tokens": 4096,
        "extra_body": {"chat_template_kwargs": {"enable_thinking": False}},
    }

    resp = http_post_json(endpoint, payload, headers={"Authorization": f"Bearer {api_key}"})

    choices = resp.get("choices")
    if not isinstance(choices, list) or not choices:
        raise RuntimeError("LiteLLM response missing choices")

    message = choices[0].get("message", {})
    content = message.get("content")

    if isinstance(content, list):
        text_parts: list[str] = []
        for part in content:
            if isinstance(part, dict):
                text_parts.append(str(part.get("text", "")))
            else:
                text_parts.append(str(part))
        content = "".join(text_parts)

    content_text = str(content or "").strip()
    if not content_text:
        raise RuntimeError("LiteLLM returned empty content")

    raw_report = parse_litellm_report_json(content_text)
    return normalize_report_payload(raw_report, report_date, news_top_n, items)


def make_card_shell(title: str) -> dict[str, Any]:
    return {
        "config": {
            "enable_forward": True,
            "update_multi": True,
            "wide_screen_mode": True,
        },
        "header": {
            "template": "blue",
            "title": {"tag": "plain_text", "content": title},
        },
        "elements": [],
    }


def add_section_title(elements: list[dict[str, Any]], title: str) -> None:
    elements.append({"tag": "div", "text": {"tag": "plain_text", "content": title}})


def add_markdown(elements: list[dict[str, Any]], content: str) -> None:
    elements.append({"tag": "markdown", "content": content})


def add_button(elements: list[dict[str, Any]], text: str, url: str, btn_type: str = "default") -> None:
    elements.append(
        {
            "tag": "action",
            "actions": [
                {
                    "tag": "button",
                    "text": {"tag": "plain_text", "content": text},
                    "url": url,
                    "type": btn_type,
                }
            ],
        }
    )


def build_single_interactive_card(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])

    card = make_card_shell(title)
    elements = card["elements"]

    add_section_title(elements, "一、今日摘要")
    add_markdown(elements, "\n".join(f"- {line}" for line in summary[:5]) or "- 暂无摘要")
    elements.append({"tag": "hr"})

    add_section_title(elements, f"二、重要新闻 Top {len(top_news)}")
    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue

        add_markdown(
            elements,
            "\n".join(
                [
                    f"**{idx}. {news.get('title', '未命名新闻')}**",
                    f"发生了什么：{news.get('what_happened', '仍需观察。')}",
                    f"为什么重要：{news.get('why_important', '仍需观察。')}",
                    f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}",
                    f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}",
                    f"来源：{news.get('source_name', '来源')}",
                ]
            ),
        )

        source_url = clean_text(news.get("source_url", ""))
        if source_url:
            add_button(elements, "查看来源", source_url, btn_type="primary")

        if idx != len(top_news):
            elements.append({"tag": "hr"})

    note_text = f"数据源：{source_json_name}"
    if used_fallback_cache:
        note_text += "（目标日期缺失，已使用最近缓存）"
    elements.append({"tag": "note", "elements": [{"tag": "plain_text", "content": note_text}]})

    return card


def build_single_post_payload(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])

    rows: list[list[dict[str, Any]]] = []

    def row_text(text: str) -> list[dict[str, Any]]:
        return [{"tag": "text", "text": text}]

    def row_link(prefix: str, label: str, href: str) -> list[dict[str, Any]]:
        row: list[dict[str, Any]] = []
        if prefix:
            row.append({"tag": "text", "text": prefix})
        row.append({"tag": "a", "text": label, "href": href})
        return row

    rows.append(row_text("一、今日摘要"))
    for line in summary[:5]:
        rows.append(row_text(f"- {line}"))

    rows.append(row_text(f"二、重要新闻 Top {len(top_news)}"))
    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue
        rows.append(row_text(f"{idx}. {news.get('title', '未命名新闻')}"))
        rows.append(row_text(f"发生了什么：{news.get('what_happened', '仍需观察。')}"))
        rows.append(row_text(f"为什么重要：{news.get('why_important', '仍需观察。')}"))
        rows.append(row_text(f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}"))
        rows.append(row_text(f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}"))

        source_name = clean_text(news.get("source_name", "来源"))
        source_url = clean_text(news.get("source_url", ""))
        if source_url:
            rows.append(row_link("来源：", source_name or "打开链接", source_url))

    note_text = f"数据源：{source_json_name}"
    if used_fallback_cache:
        note_text += "（目标日期缺失，已使用最近缓存）"
    rows.append(row_text(note_text))

    return {
        "msg_type": "post",
        "content": {
            "post": {
                "zh_cn": {
                    "title": title,
                    "content": rows,
                }
            }
        },
    }


def build_single_text_payload(
    report: dict[str, Any],
    source_json_name: str,
    used_fallback_cache: bool,
) -> dict[str, Any]:
    title = clean_text(report.get("title", "AI 科技日报"))
    summary = ensure_list_of_strings(report.get("summary"))
    top_news = report.get("top_news", [])

    lines = [title, "", "一、今日摘要"]
    lines.extend(f"- {line}" for line in summary[:5])
    lines.extend(["", f"二、重要新闻 Top {len(top_news)}"])

    for idx, news in enumerate(top_news, start=1):
        if not isinstance(news, dict):
            continue
        lines.append(f"{idx}. {news.get('title', '未命名新闻')}")
        lines.append(f"发生了什么：{news.get('what_happened', '仍需观察。')}")
        lines.append(f"为什么重要：{news.get('why_important', '仍需观察。')}")
        lines.append(f"汽车行业关联：{news.get('auto_relevance', RELATION_INDIRECT)}")
        lines.append(f"简要影响：{news.get('auto_impact_brief', '仍需观察。')}")
        lines.append(f"来源：{news.get('source_name', '来源')} {news.get('source_url', '')}")
        lines.append("")

    note_text = f"数据源：{source_json_name}"
    if used_fallback_cache:
        note_text += "（目标日期缺失，已使用最近缓存）"
    lines.append(note_text)

    return {
        "msg_type": "text",
        "content": {"text": "\n".join(lines).strip()},
    }


def feishu_sign(secret: str) -> tuple[str, str]:
    timestamp = str(int(time.time()))
    string_to_sign = f"{timestamp}\n{secret}"
    hmac_code = hmac.new(
        string_to_sign.encode("utf-8"),
        b"",
        digestmod=hashlib.sha256,
    ).digest()
    sign = base64.b64encode(hmac_code).decode("utf-8")
    return timestamp, sign


def send_feishu_payload(webhook_url: str, payload: dict[str, Any], secret: str | None = None) -> None:
    secret_value = (secret or "").strip()
    send_payload = dict(payload)

    if secret_value:
        timestamp, sign = feishu_sign(secret_value)
        send_payload["timestamp"] = timestamp
        send_payload["sign"] = sign

    resp = http_post_json(webhook_url, send_payload)
    if isinstance(resp, dict) and resp.get("code", 0) != 0:
        raise RuntimeError(f"Feishu error code={resp.get('code')} msg={resp.get('msg')}")


def send_report_with_fallback(webhook_url: str, secret: str | None, report: dict[str, Any]) -> None:
    source_json_name = clean_text(report.get("source_json_name", ""))
    used_fallback_cache = bool(report.get("used_fallback_cache", False))

    interactive_payload = {
        "msg_type": "interactive",
        "card": build_single_interactive_card(
            report=report,
            source_json_name=source_json_name,
            used_fallback_cache=used_fallback_cache,
        ),
    }

    try:
        LOGGER.info("Sending one Feishu interactive card")
        send_feishu_payload(webhook_url, interactive_payload, secret=secret)
        return
    except Exception as exc:
        LOGGER.warning("Interactive card send failed, fallback to post. reason=%s", exc)

    post_payload = build_single_post_payload(
        report=report,
        source_json_name=source_json_name,
        used_fallback_cache=used_fallback_cache,
    )

    try:
        LOGGER.info("Sending one Feishu post message")
        send_feishu_payload(webhook_url, post_payload, secret=secret)
        return
    except Exception as exc:
        LOGGER.warning("Post message send failed, fallback to text. reason=%s", exc)

    text_payload = build_single_text_payload(
        report=report,
        source_json_name=source_json_name,
        used_fallback_cache=used_fallback_cache,
    )
    LOGGER.info("Sending one Feishu text message")
    send_feishu_payload(webhook_url, text_payload, secret=secret)


def build_error_report(report_date: str, detail: str) -> dict[str, Any]:
    return {
        "title": f"AI 科技日报｜{report_date}",
        "report_date": report_date,
        "summary": [f"日报生成失败：{truncate_text(detail, 180)}"],
        "top_news": [],
    }


def main() -> int:
    setup_logging()
    project_root = Path(__file__).resolve().parents[1]
    load_dotenv_file(project_root / ".env")

    timezone_name = os.getenv("TIMEZONE", DEFAULT_TIMEZONE)
    news_max_chars = parse_int_env("NEWS_MAX_CHARS", DEFAULT_NEWS_MAX_CHARS)
    news_top_n = parse_int_env("NEWS_TOP_N", DEFAULT_NEWS_TOP_N)

    tz = get_timezone(timezone_name)
    now_local = datetime.now(tz)
    report_date = (now_local - timedelta(days=1)).date().isoformat()

    webhook_url = os.getenv("FEISHU_WEBHOOK_URL", "").strip()
    if not webhook_url:
        raise RuntimeError("Missing FEISHU_WEBHOOK_URL")
    feishu_secret = os.getenv("FEISHU_BOT_SECRET")

    data_dir = project_root / "data" / "news-candidates"
    if not data_dir.exists():
        error_report = build_error_report(report_date, f"目录不存在：{data_dir.as_posix()}")
        error_report["source_json_name"] = "N/A"
        error_report["used_fallback_cache"] = False
        send_report_with_fallback(webhook_url, feishu_secret, error_report)
        return 1

    try:
        candidates_payload, source_file, used_fallback_cache = find_candidates_json(data_dir, report_date)
    except Exception as exc:
        error_report = build_error_report(report_date, str(exc))
        error_report["source_json_name"] = "N/A"
        error_report["used_fallback_cache"] = False
        send_report_with_fallback(webhook_url, feishu_secret, error_report)
        return 1

    items = candidates_payload.get("items", [])
    if not isinstance(items, list):
        raise RuntimeError("Invalid candidates JSON: items is not a list")

    if not items:
        empty_report = build_error_report(report_date, f"候选新闻为空：{source_file.name}")
        empty_report["source_json_name"] = source_file.name
        empty_report["used_fallback_cache"] = used_fallback_cache
        send_report_with_fallback(webhook_url, feishu_secret, empty_report)
        return 0

    api_key = os.getenv("LITELLM_API_KEY") or os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("Missing LITELLM_API_KEY or OPENAI_API_KEY")

    base_url = os.getenv("LITELLM_BASE_URL", "").strip()
    if not base_url:
        raise RuntimeError("Missing LITELLM_BASE_URL")

    model = os.getenv("LITELLM_MODEL", "gpt-5.4").strip() or "gpt-5.4"

    LOGGER.info(
        "Generating report JSON from %s (items=%s, fallback_cache=%s)",
        source_file.name,
        len(items),
        used_fallback_cache,
    )

    try:
        report = create_report_json_with_litellm(
            base_url=base_url,
            api_key=api_key,
            model=model,
            report_date=report_date,
            timezone_name=timezone_name,
            news_top_n=news_top_n,
            news_max_chars=news_max_chars,
            items=items,
            source_json_name=source_file.name,
            used_fallback_cache=used_fallback_cache,
        )
    except LiteLLMReportParseError as exc:
        LOGGER.warning("LiteLLM JSON parse failed: %s", exc)
        error_report = build_error_report(report_date, f"LiteLLM JSON 解析失败：{exc}")
        error_report["source_json_name"] = source_file.name
        error_report["used_fallback_cache"] = used_fallback_cache
        text_payload = build_single_text_payload(
            report=error_report,
            source_json_name=source_file.name,
            used_fallback_cache=used_fallback_cache,
        )
        send_feishu_payload(webhook_url, text_payload, secret=feishu_secret)
        return 1
    except Exception as exc:
        LOGGER.warning("LiteLLM JSON generation failed: %s", exc)
        error_report = build_error_report(report_date, f"LiteLLM 生成失败：{exc}")
        error_report["source_json_name"] = source_file.name
        error_report["used_fallback_cache"] = used_fallback_cache
        send_report_with_fallback(webhook_url, feishu_secret, error_report)
        return 1

    report = shrink_report_for_limit(report, news_max_chars, news_top_n)
    report["source_json_name"] = source_file.name
    report["used_fallback_cache"] = used_fallback_cache

    send_report_with_fallback(webhook_url=webhook_url, secret=feishu_secret, report=report)
    LOGGER.info("Daily report sent successfully")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        LOGGER.error("Run failed: %s", exc)
        raise SystemExit(1)
